(() => {
  if(window.__ironSixMusicLoaded)return;
  window.__ironSixMusicLoaded=true;
  const GENRES=['Electronic','Hip-Hop/Rap','Rock','Metal','House','Techno','Drum & Bass','Dubstep','Hardstyle','Future Bass'];
  const state={tracks:[],index:-1,genre:'Electronic',mode:'radio',playing:false};
  const audio=new Audio();audio.preload='none';
  const originals=Array.isArray(window.IRON_SIX_ORIGINALS)?window.IRON_SIX_ORIGINALS:[];
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function savePrefs(){try{localStorage.setItem('ironSixMusicPrefs',JSON.stringify({genre:state.genre,volume:audio.volume}))}catch(_){}}
  function loadPrefs(){try{const p=JSON.parse(localStorage.getItem('ironSixMusicPrefs')||'{}');if(GENRES.includes(p.genre))state.genre=p.genre;if(Number.isFinite(Number(p.volume)))audio.volume=Math.max(0,Math.min(1,Number(p.volume)))}catch(_){}}
  loadPrefs();
  function workoutGenre(){try{const u=typeof activeUser==='function'?activeUser():null;if(u?.trainingMode==='circuit')return Number(u?.readiness?.energy||4)<=2?'House':'Drum & Bass';const key=String(u?.program?.currentWorkoutKey||'').toLowerCase();if(key.includes('lower'))return 'Hip-Hop/Rap';if(key.includes('shoulder')||key.includes('upper'))return 'Rock';return 'Electronic'}catch(_){return 'Electronic'}}
  function injectStyle(){if(document.getElementById('ironSixMusicStyle'))return;const s=document.createElement('style');s.id='ironSixMusicStyle';s.textContent=`.music-card{border:1px solid var(--line);border-radius:16px;background:var(--surface);padding:13px;margin-top:10px}.music-source-row,.music-controls,.music-genres{display:flex;gap:8px;flex-wrap:wrap}.music-source-row{margin-bottom:10px}.music-chip,.music-control{border:1px solid var(--line);background:var(--surface2);color:var(--text);border-radius:999px;padding:8px 11px;font-size:11px;font-weight:750}.music-chip.active{border-color:var(--accent);background:rgba(157,223,104,.12)}.music-now{display:grid;grid-template-columns:54px 1fr;gap:11px;align-items:center;margin:11px 0}.music-art{width:54px;height:54px;border-radius:10px;background:var(--surface2);object-fit:cover}.music-title{font-weight:800;font-size:13px}.music-meta{font-size:11px;color:var(--muted);margin-top:3px}.music-controls{align-items:center}.music-control.primary{background:var(--accent);color:#0b0c0f;border-color:var(--accent)}.music-volume{width:95px}.music-note{font-size:10px;color:var(--muted);line-height:1.4;margin-top:9px}.music-status{font-size:11px;color:var(--muted);margin-top:8px}.music-originals-empty{font-size:12px;color:var(--muted);padding:8px 0}.music-link{color:var(--accent);text-decoration:none;font-size:11px;font-weight:750}`;document.head.appendChild(s)}
  function ensureUI(){const today=document.getElementById('today');if(!today||document.getElementById('workoutMusic'))return;injectStyle();const section=document.createElement('div');section.className='section';section.id='workoutMusic';section.innerHTML=`<div class="section-head"><div><h2>Workout music</h2><small>Free radio, Iron Six originals, or your own service</small></div></div><div class="music-card"><div class="music-source-row"><button class="music-chip active" data-music-mode="radio">Iron Six Radio</button><button class="music-chip" data-music-mode="originals">Iron Six Originals</button><button class="music-chip" data-music-mode="spotify">Spotify</button></div><div id="musicRadio"><div class="music-genres"><button class="music-chip" data-music-match>Match workout</button>${GENRES.map(g=>`<button class="music-chip ${g===state.genre?'active':''}" data-music-genre="${esc(g)}">${esc(g)}</button>`).join('')}</div><div class="music-now" id="musicNow"><div class="music-art"></div><div><div class="music-title">Choose a station</div><div class="music-meta">Audius tracks with commercial-use licenses only</div></div></div><div class="music-controls"><button class="music-control" data-music-prev>◀</button><button class="music-control primary" data-music-play>Play</button><button class="music-control" data-music-next>▶</button><input class="music-volume" type="range" min="0" max="1" step="0.05" value="${audio.volume}" aria-label="Music volume"></div><div class="music-status" id="musicStatus"></div><div class="music-note">Radio only includes tracks whose Audius metadata indicates commercial use is allowed. Artist/title attribution stays visible while playing.</div></div><div id="musicOriginals" hidden></div><div id="musicSpotify" hidden><p class="music-meta">Open Spotify and keep using your existing account. Iron Six does not require Spotify for workout music.</p><a class="btn secondary" href="https://open.spotify.com/" target="_blank" rel="noopener noreferrer">Open Spotify</a></div></div>`;const first=today.querySelector('.section');if(first)first.insertAdjacentElement('afterend',section);else today.appendChild(section);bind(section);renderOriginals()}
  function apiUrl(){return `/api/music?genre=${encodeURIComponent(state.genre)}`}
  async function loadRadio(autoPlay=false){const status=document.getElementById('musicStatus');if(status)status.textContent='Finding commercially usable tracks…';try{const r=await fetch(apiUrl());const body=await r.json();if(!r.ok)throw Error(body?.error||'Radio unavailable');state.tracks=Array.isArray(body.tracks)?body.tracks:[];state.index=state.tracks.length?0:-1;if(!state.tracks.length)throw Error('No commercially licensed tracks found for this station right now.');setTrack(state.index,autoPlay);if(status)status.textContent=`${state.tracks.length} licensed tracks loaded from Audius.`}catch(err){if(status)status.textContent=String(err.message||err);state.tracks=[];state.index=-1;renderNow()}}
  function setTrack(index,play=false){if(!state.tracks.length)return;state.index=(index+state.tracks.length)%state.tracks.length;const t=state.tracks[state.index];audio.src=t.stream;renderNow();if(play)audio.play().catch(()=>{})}
  function renderNow(){const box=document.getElementById('musicNow'),t=state.tracks[state.index];if(!box)return;if(!t){box.innerHTML='<div class="music-art"></div><div><div class="music-title">Choose a station</div><div class="music-meta">Audius tracks with commercial-use licenses only</div></div>';return}box.innerHTML=`${t.artwork?`<img class="music-art" src="${esc(t.artwork)}" alt="">`:'<div class="music-art"></div>'}<div><div class="music-title">${esc(t.title)}</div><div class="music-meta">${esc(t.artist)}${t.bpm?` · ${t.bpm} BPM`:''}${t.license?` · ${esc(t.license)}`:''}</div>${t.permalink?`<a class="music-link" href="${esc(t.permalink)}" target="_blank" rel="noopener noreferrer">View on Audius</a>`:''}</div>`}
  function renderOriginals(){const box=document.getElementById('musicOriginals');if(!box)return;if(!originals.length){box.innerHTML='<div class="music-originals-empty">Iron Six Originals is ready for our own licensed workout tracks. The player is built; the catalog will populate as tracks are added.</div>';return}box.innerHTML=originals.map((t,i)=>`<button class="music-control" data-original-index="${i}">${esc(t.title||`Original ${i+1}`)}</button>`).join(' ')}
  function setMode(mode){state.mode=mode;document.querySelectorAll('[data-music-mode]').forEach(b=>b.classList.toggle('active',b.dataset.musicMode===mode));document.getElementById('musicRadio').hidden=mode!=='radio';document.getElementById('musicOriginals').hidden=mode!=='originals';document.getElementById('musicSpotify').hidden=mode!=='spotify'}
  function chooseGenre(genre,root,play=true){state.genre=GENRES.includes(genre)?genre:'Electronic';root.querySelectorAll('[data-music-genre]').forEach(b=>b.classList.toggle('active',b.dataset.musicGenre===state.genre));savePrefs();loadRadio(play)}
  function bind(root){root.addEventListener('click',e=>{const mode=e.target.closest('[data-music-mode]');if(mode){setMode(mode.dataset.musicMode);return}if(e.target.closest('[data-music-match]')){chooseGenre(workoutGenre(),root,true);return}const g=e.target.closest('[data-music-genre]');if(g){chooseGenre(g.dataset.musicGenre,root,true);return}if(e.target.closest('[data-music-play]')){if(!audio.src){loadRadio(true);return}audio.paused?audio.play().catch(()=>{}):audio.pause();return}if(e.target.closest('[data-music-next]')){setTrack(state.index+1,true);return}if(e.target.closest('[data-music-prev]')){setTrack(state.index-1,true);return}const oi=e.target.closest('[data-original-index]');if(oi){const t=originals[Number(oi.dataset.originalIndex)];if(t?.src){state.tracks=[{title:t.title||'Iron Six Original',artist:'Iron Six',stream:t.src,artwork:t.artwork||'',license:t.license||'Iron Six licensed original'}];setTrack(0,true)}}});root.querySelector('.music-volume')?.addEventListener('input',e=>{audio.volume=Number(e.target.value);savePrefs()})}
  audio.addEventListener('play',()=>{state.playing=true;const b=document.querySelector('[data-music-play]');if(b)b.textContent='Pause'});audio.addEventListener('pause',()=>{state.playing=false;const b=document.querySelector('[data-music-play]');if(b)b.textContent='Play'});audio.addEventListener('ended',()=>setTrack(state.index+1,true));audio.addEventListener('error',()=>{const s=document.getElementById('musicStatus');if(s)s.textContent='This track could not be streamed. Skipping…';if(state.tracks.length>1)setTimeout(()=>setTrack(state.index+1,true),500)});
  window.IronSixMusic={loadRadio,setMode,state,audio,workoutGenre};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ensureUI);else ensureUI();
})();
