/* Camera rep counting + conservative form observations + opt-in voice workout controls.
   Off unless explicitly enabled with ?pose=1 or localStorage ironSixPoseSpike=1.
   v5 adds a local person-detector anchor and runs pose inference inside the locked user's ROI.
   Video, detections and pose landmarks stay on-device. */
(() => {
  const FLAG='ironSixPoseSpike';
  const VISION='https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@1.0.1/vision_bundle.mjs';
  const WASM='https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@1.0.1/wasm';
  const MODEL='https://storage.googleapis.com/mediapipe-models/pose_landmarker/pose_landmarker_lite/float16/1/pose_landmarker_lite.task';
  const PERSON_MODEL='https://storage.googleapis.com/mediapipe-tasks/object_detector/efficientdet_lite0_uint8.tflite';
  const PERSON_DETECT_MS=240;
  function readFlag(){let stored=null;try{stored=localStorage.getItem(FLAG)}catch(_){}const query=new URLSearchParams(location.search||'').get('pose');if(query==='1'||query==='0'){stored=query;try{localStorage.setItem(FLAG,query)}catch(_){}}return stored==='1'}
  if(!readFlag())return;

  const counterApi=window.IronSixRepCounter;let formApi=window.IronSixFormCoach,voiceApi=window.IronSixWorkoutVoice,isolationApi=window.IronSixPersonIsolation;
  if(!counterApi)return;
  function helperUrl(src){const url=new URL(src,location.href),share=new URLSearchParams(location.search||'').get('_vercel_share');if(share&&!url.searchParams.has('_vercel_share'))url.searchParams.set('_vercel_share',share);return url.href}
  function loadHelper(src,globalName,ready){if(window[globalName])return queueMicrotask(()=>ready(window[globalName]));const script=document.createElement('script');script.src=helperUrl(src);script.async=true;script.onload=()=>{const api=window[globalName];if(api)ready(api);else console.error(`[Iron Six] ${globalName} loaded without registering its API.`)};script.onerror=()=>console.error(`[Iron Six] Failed to load ${src}.`);document.head.appendChild(script)}
  loadHelper('pose-person-isolation.js','IronSixPersonIsolation',api=>{isolationApi=api;if(rule&&!personTracker)personTracker=api.createPersonTracker()});
  loadHelper('pose-form-coach.js','IronSixFormCoach',api=>{formApi=api;if(rule&&!formEvaluator){formEvaluator=formApi?.createEvaluator?.(rule)||null;formState=formEvaluator?.state?.()||null;paintForm(formState)}});
  loadHelper('workout-voice.js','IronSixWorkoutVoice',api=>{voiceApi=api});

  let sheet=null,video=null,canvas=null,landmarker=null,personDetector=null,stream=null,counter=null,rule=null,target=null,exercise=null,raf=0,wake=null;
  let framesSeen=0,framesTracked=0,startedAt=0,fps=0,lastFrameAt=0,lastVideoTime=-1,loading=false,detectorFrames=0,roiFrames=0,lastPersonDetectAt=-Infinity;
  let tracker=null,tracking=null,personTracker=null,personState=null,roiCanvas=null,formEvaluator=null,formState=null,sessionId=0;
  let voiceEnabled=false,voiceRun=0,voiceRecognizer=null,voiceMode=null,lastTranscript='';
  const el=id=>document.getElementById(id),setText=(id,value)=>{const node=el(id);if(node)node.textContent=value},sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));

  function injectStyles(){if(el('poseAssistStyles'))return;const style=document.createElement('style');style.id='poseAssistStyles';style.textContent=`
    .pose-modal{max-width:720px}.pose-head{display:flex;justify-content:space-between;gap:14px;align-items:flex-start}.pose-head h3{margin:0 0 5px}.pose-head p{margin:0 0 6px}.pose-count{text-align:center;min-width:72px;background:var(--surface2);border:1px solid var(--line);border-radius:15px;padding:9px}.pose-count strong{display:block;font-size:28px;line-height:1}.pose-count span{display:block;color:var(--muted);font-size:11px;margin-top:4px}
    .pose-stage{position:relative;overflow:hidden;border-radius:16px;background:#050607;aspect-ratio:var(--pose-stage-ratio,3/4);margin:12px auto;width:100%}.pose-stage video,.pose-stage canvas{position:absolute;inset:0;width:100%;height:100%;object-fit:contain;transform:scaleX(-1)}.pose-stage canvas{pointer-events:none}.pose-status{position:absolute;left:10px;right:10px;bottom:10px;background:rgba(5,6,7,.78);border:1px solid rgba(255,255,255,.13);border-radius:11px;padding:8px 10px;font-size:12px;font-weight:750;backdrop-filter:blur(8px)}
    .pose-readout-row{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-top:9px}.pose-readout{font-size:11px;color:var(--muted);line-height:1.45}.pose-copy{border:1px solid var(--line);background:var(--surface2);color:var(--text);border-radius:10px;padding:8px 10px;font-size:11px;font-weight:800;white-space:nowrap}.pose-caution{color:#ffd18a!important}.pose-privacy{margin-top:10px}.pose-form{margin-top:10px;border:1px solid var(--line);background:var(--surface2);border-radius:14px;padding:11px 12px}.pose-form strong{display:block;font-size:12px;margin-bottom:4px}.pose-form span{display:block;font-size:12px;line-height:1.45;color:var(--muted)}.pose-form.cue{border-color:rgba(46,229,128,.5)}.pose-form.watch{border-color:rgba(255,209,138,.45)}
    .pose-voice{display:grid;grid-template-columns:auto 1fr;gap:10px;align-items:center;margin-top:10px;border:1px solid var(--line);border-radius:14px;padding:10px 11px}.pose-voice button{min-width:118px}.pose-voice-text{min-width:0}.pose-voice-text strong{display:block;font-size:12px}.pose-voice-text span{display:block;color:var(--muted);font-size:11px;line-height:1.4;margin-top:2px}.pose-voice.on{border-color:rgba(46,229,128,.5);background:rgba(46,229,128,.055)}.pose-bar{display:flex;align-items:center;gap:9px;flex-wrap:wrap;margin-top:11px;padding-top:11px;border-top:1px solid var(--line)}.pose-bar button{border:1px solid rgba(46,229,128,.35);background:rgba(46,229,128,.08);color:var(--accent);border-radius:11px;padding:9px 11px;font-weight:800}.pose-bar span{font-size:11px;color:var(--muted)}
    @media(min-width:700px){.pose-stage{max-width:520px}}@media(max-width:520px){.pose-modal{padding:14px}.pose-stage{margin:9px auto}.pose-voice{grid-template-columns:1fr}.pose-voice button{width:100%}.pose-readout-row{align-items:flex-start}}
  `;document.head.appendChild(style)}
  function build(){if(sheet)return sheet;injectStyles();sheet=document.createElement('div');sheet.className='modal-backdrop pose-sheet';sheet.id='poseSheet';sheet.setAttribute('role','dialog');sheet.setAttribute('aria-modal','true');sheet.setAttribute('aria-label','Camera workout assistant');sheet.innerHTML=`<div class="modal pose-modal"><div class="pose-head"><div><h3 id="poseTitle">Camera workout assistant</h3><p id="poseSetup">Setting up the camera…</p><p class="pose-caution" id="poseCaution" hidden></p></div><div class="pose-count"><strong id="poseReps">0</strong><span>reps</span></div></div><div class="pose-stage" id="poseStage"><video id="poseVideo" playsinline muted autoplay></video><canvas id="poseCanvas"></canvas><div class="pose-status" id="poseStatus">Starting…</div></div><div class="pose-readout-row"><span class="pose-readout" id="poseReadout"></span><button type="button" class="pose-copy" id="poseCopy">Copy diagnostics</button></div><div class="pose-readout-row"><span class="helper" id="poseLock" role="status">Centre yourself and hold still to lock.</span><button type="button" class="pose-copy" id="poseRelock">Re-lock user</button></div><div class="pose-form" id="poseForm"><strong>Form watch</strong><span id="poseFormCue">Waiting for a completed rep. Camera-visible observations only.</span></div><div class="pose-voice" id="poseVoice"><button type="button" class="btn secondary" id="poseVoiceToggle">Enable voice</button><div class="pose-voice-text"><strong id="poseVoiceState">Voice is off</strong><span id="poseVoiceHint">Try “185 pounds”, “8 reps”, “RIR 2”, or “set done”.</span></div></div><div class="helper">Tracking v5 · Person-isolated ROI + motion-aware working-side pose. A person lock can survive short pose dropouts; reps are never invented across an unseen movement.</div><div class="helper pose-privacy">Video, person boxes and pose landmarks stay on this device. Voice is optional; transcription uses your browser/device speech service and may use its network service. Iron Six does not store microphone audio.</div><div class="cta"><button type="button" class="btn secondary" id="poseClose">Close</button><button type="button" class="btn primary" id="poseUse" disabled>Use count only</button></div></div>`;document.body.appendChild(sheet);video=el('poseVideo');canvas=el('poseCanvas');el('poseClose').addEventListener('click',close);el('poseUse').addEventListener('click',useCount);el('poseCopy').addEventListener('click',copyDiagnostics);el('poseRelock').addEventListener('click',relock);el('poseVoiceToggle').addEventListener('click',toggleVoice);sheet.addEventListener('click',event=>{if(event.target===sheet)close()});return sheet}
  function fail(message){setText('poseStatus',message);setText('poseSetup',message)}
  function relock(){if(!tracker||!counter)return;personTracker?.reset?.();tracker.reset();counter.interrupt();tracking=null;personState=null;formEvaluator?.interrupt(counter.state().log.length);formState=formEvaluator?.state?.()||null;setText('poseLock','Centre yourself and hold still to lock.');setText('poseStatus','Re-locking. Completed reps are kept.');if(canvas)canvas.getContext('2d')?.clearRect(0,0,canvas.width,canvas.height)}

  async function loadModel(){
    if(landmarker)return landmarker;const vision=await import(VISION),files=await vision.FilesetResolver.forVisionTasks(WASM),poseOptions={baseOptions:{modelAssetPath:MODEL,delegate:'GPU'},runningMode:'VIDEO',numPoses:3,minPoseDetectionConfidence:0.45,minPosePresenceConfidence:0.45,minTrackingConfidence:0.5};
    try{landmarker=await vision.PoseLandmarker.createFromOptions(files,poseOptions)}catch(_){landmarker=await vision.PoseLandmarker.createFromOptions(files,{...poseOptions,baseOptions:{...poseOptions.baseOptions,delegate:'CPU'}})}
    if(vision.ObjectDetector&&isolationApi){const detectorOptions={baseOptions:{modelAssetPath:PERSON_MODEL,delegate:'GPU'},runningMode:'VIDEO',maxResults:4,scoreThreshold:0.35,categoryAllowlist:['person']};try{personDetector=await vision.ObjectDetector.createFromOptions(files,detectorOptions)}catch(_){try{personDetector=await vision.ObjectDetector.createFromOptions(files,{...detectorOptions,baseOptions:{...detectorOptions.baseOptions,delegate:'CPU'}})}catch(__){personDetector=null}}}
    return landmarker;
  }
  function syncStageAspect(){const stage=el('poseStage');if(!stage||!video?.videoWidth||!video?.videoHeight)return;stage.style.setProperty('--pose-stage-ratio',`${video.videoWidth}/${video.videoHeight}`);stage.dataset.orientation=video.videoHeight>=video.videoWidth?'portrait':'landscape'}
  async function startCamera(id){if(!navigator.mediaDevices||!navigator.mediaDevices.getUserMedia)throw new Error('This browser/app cannot open the camera. Camera permission and a secure page are required.');const portrait=(window.innerHeight||0)>=(window.innerWidth||0),acquired=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'user'},width:{ideal:portrait?720:1280},height:{ideal:portrait?1280:720},aspectRatio:{ideal:portrait?9/16:16/9},frameRate:{ideal:30,max:30}},audio:false});if(id!==sessionId){for(const track of acquired.getTracks())track.stop();return}stream=acquired;video.srcObject=stream;await video.play().catch(()=>{});if(!video.videoWidth)await new Promise(resolve=>{video.addEventListener('loadedmetadata',resolve,{once:true});setTimeout(resolve,3000)});syncStageAspect()}
  async function keepAwake(id){try{if(navigator.wakeLock){const acquired=await navigator.wakeLock.request('screen');if(id!==sessionId)await acquired.release();else wake=acquired}}catch(_){}}
  function release(){if(wake){wake.release().catch(()=>{});wake=null}}
  function cropSource(roi){if(!roi||!video?.videoWidth||!video?.videoHeight)return video;if(!roiCanvas)roiCanvas=document.createElement('canvas');const sw=Math.max(2,roi.w*video.videoWidth),sh=Math.max(2,roi.h*video.videoHeight),scale=Math.min(1,560/Math.max(sw,sh));roiCanvas.width=Math.max(96,Math.round(sw*scale));roiCanvas.height=Math.max(96,Math.round(sh*scale));const ctx=roiCanvas.getContext('2d',{alpha:false});if(!ctx)return video;ctx.drawImage(video,roi.x*video.videoWidth,roi.y*video.videoHeight,sw,sh,0,0,roiCanvas.width,roiCanvas.height);roiFrames++;return roiCanvas}
  function updatePersonDetection(now){if(!personDetector||!personTracker||now-lastPersonDetectAt<PERSON_DETECT_MS)return;lastPersonDetectAt=now;try{const result=personDetector.detectForVideo(video,now),boxes=isolationApi.normalizeDetections(result,video.videoWidth,video.videoHeight);personState=personTracker.push(boxes,now);detectorFrames++}catch(_){}}
  function runPose(now,roi){const source=cropSource(roi);let poses=[];try{poses=landmarker.detectForVideo(source,now)?.landmarks||[]}catch(_){}if(roi&&source!==video&&isolationApi)poses=isolationApi.remapLandmarks(poses,roi);return poses}

  function tick(){
    raf=requestAnimationFrame(tick);if(!landmarker||!video||video.readyState<2||!video.videoWidth)return;if(video.currentTime===lastVideoTime)return;lastVideoTime=video.currentTime;const now=performance.now();if(lastFrameAt)fps=fps?fps*0.9+(1000/Math.max(1,now-lastFrameAt))*0.1:1000/Math.max(1,now-lastFrameAt);lastFrameAt=now;
    updatePersonDetection(now);if(personTracker)personState=personTracker.sample(now);const roi=personState?.locked&&!personState.needsRelock?personState.roi:null,poses=runPose(now,roi);if(personTracker&&personState?.locked&&poses.length)personState=personTracker.observePose(poses[0],now);
    const aspect=video.videoWidth/video.videoHeight,subjectPresent=!!personState?.locked&&!personState?.needsRelock;tracking=tracker.push(poses,now,aspect,{subjectPresent,personBox:personState?.box||null});const landmarks=tracking.landmarks;framesSeen++;if(landmarks)framesTracked++;
    if(!landmarks&&!subjectPresent){counter.interrupt();formEvaluator?.interrupt(counter.state().log.length)}
    // Framing is decided before the frame is counted, not after it is displayed: a lifter half
    // out of shot produces joint angles that look entirely plausible and are wrong. Side-aware,
    // so a locked working side is judged on the joints that side actually needs.
    const framed=landmarks?counterApi.framing(rule,landmarks,tracking.side,0.42):{ok:false,missing:[],message:'No one in frame yet.'};
    const state=counter.push({landmarks,t:now,aspect,side:tracking.side,subjectPresent,minVisibility:0.42,framed:framed.ok});if(formEvaluator)formState=formEvaluator.push({landmarks,side:tracking.side,t:now,aspect,counterState:state});const frame={ok:!!landmarks&&framed.ok,message:tracking.message||personState?.message||(framed.ok?'':framed.message)};setText('poseLock',subjectPresent&&!landmarks?'User isolated · pose reacquiring…':(tracking.message||personState?.message));draw(landmarks,state);paint(state,frame);paintForm(formState);
  }
  function paint(state,frame){setText('poseReps',String(state.reps));const use=el('poseUse');if(use){use.disabled=!state.reps;use.textContent=state.reps?('Use '+state.reps+' reps only'):'Use count only'}const status=!frame.ok?(frame.message||'Pose reacquiring…'):(state.message||{waiting:'Stand at the top to start.',top:'Ready.',descending:'Down…',bottom:'Bottom.',ascending:'Up…',lost:'Lost you.'}[state.phase]||'Tracking.');setText('poseStatus',status);const tracked=framesSeen?Math.round(framesTracked/framesSeen*100):0,durations=state.log.map(r=>r.ms),average=durations.length?Math.round(durations.reduce((a,b)=>a+b,0)/durations.length):0;setText('poseReadout',[video?.videoWidth&&video?.videoHeight?`${video.videoWidth}×${video.videoHeight}`:'no video size',`${Math.round(fps)} fps`,`${tracked}% pose`,personState?.locked?'person locked':'person search',roiFrames?`${Math.round(roiFrames/Math.max(1,framesSeen)*100)}% ROI`:'full frame',state.angle===null?'no angle':`${state.angle}°`,state.rejected?`${state.rejected} rejected`:'0 rejected',average?`avg rep ${(average/1000).toFixed(1)}s`:'—'].join(' · '))}
  function paintForm(state){const box=el('poseForm');if(!box)return;box.classList.remove('cue','watch');let text=formEvaluator?'Form watch active — complete a rep with your working side visible.':'Form watch is loading…';if(state?.repeatedCue){box.classList.add(state.repeatedCue.level==='cue'?'cue':'watch');text='Coach cue: '+state.repeatedCue.text}else if(state?.latest?.cues?.length){const cue=state.latest.cues[0];box.classList.add(cue.level==='cue'?'cue':'watch');text='Rep '+state.latest.index+' suggestion: '+cue.text}else if(state?.latest){const samples=Number(state.latest.samples)||0;if(samples<8){box.classList.add('watch');text='Rep '+state.latest.index+' counted, but form analysis was skipped because only '+samples+' clean frames were available. Keep your working side visible and try again.'}else{text='Rep '+state.latest.index+' analyzed: no camera-visible issue crossed the cue threshold. Keep the same controlled depth and torso path.'}}setText('poseFormCue',text)}
  function drawIsolation(context){const b=personState?.box;if(!b||!canvas)return;context.save();context.strokeStyle=personState?.needsRelock?'#ff8b8b':'#2ee580';context.lineWidth=Math.max(2,canvas.width/320);context.setLineDash([Math.max(7,canvas.width/90),Math.max(5,canvas.width/130)]);context.strokeRect(b.x*canvas.width,b.y*canvas.height,b.w*canvas.width,b.h*canvas.height);context.restore()}
  function draw(landmarks,state){if(!canvas)return;if(canvas.width!==video.videoWidth||canvas.height!==video.videoHeight){canvas.width=video.videoWidth;canvas.height=video.videoHeight}const context=canvas.getContext('2d');if(!context)return;context.clearRect(0,0,canvas.width,canvas.height);drawIsolation(context);if(!landmarks)return;const toPixels=point=>[point.x*canvas.width,point.y*canvas.height],good=state.phase!=='lost'&&state.phase!=='waiting';context.strokeStyle=good?'#2ee580':'#ff8b8b';context.fillStyle=context.strokeStyle;context.lineWidth=Math.max(3,canvas.width/220);const side=tracking?.side??0,selectedChain=rule.joint[side],chains=rule.id==='squat'?[[side?12:11,side?24:23],selectedChain]:[selectedChain];for(const chain of chains){const points=chain.map(index=>landmarks[index]);if(points.some(point=>!point||(point.visibility!==undefined&&point.visibility<counterApi.MIN_VISIBILITY)))continue;context.beginPath();points.forEach((point,index)=>{const [x,y]=toPixels(point);index?context.lineTo(x,y):context.moveTo(x,y)});context.stroke();for(const point of points){const [x,y]=toPixels(point);context.beginPath();context.arc(x,y,context.lineWidth*1.5,0,Math.PI*2);context.fill()}}if(state.angle!==null&&landmarks[selectedChain[1]]){const [ax,ay]=toPixels(landmarks[selectedChain[1]]);context.save();context.scale(-1,1);context.font=`700 ${Math.round(canvas.width/24)}px system-ui,sans-serif`;context.textAlign='left';context.fillText(`${state.angle}°`,-ax+18,ay-14);context.restore()}}

  function voiceSupported(){return !!(window.IronSixNative?.listenVoice||(window.SpeechRecognition||window.webkitSpeechRecognition))}
  function setVoiceUi(title,hint){setText('poseVoiceState',title);if(hint!==undefined)setText('poseVoiceHint',hint);const box=el('poseVoice'),button=el('poseVoiceToggle');box?.classList.toggle('on',voiceEnabled);if(button)button.textContent=voiceEnabled?'Disable voice':'Enable voice'}
  async function listenWebOnce(token){const Ctor=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Ctor)throw new Error('Speech recognition is not available in this browser.');return new Promise((resolve,reject)=>{const recognition=new Ctor();voiceRecognizer=recognition;let settled=false;const finish=value=>{if(settled)return;settled=true;if(voiceRecognizer===recognition)voiceRecognizer=null;resolve(value)},failVoice=error=>{if(settled)return;settled=true;if(voiceRecognizer===recognition)voiceRecognizer=null;reject(error)};recognition.lang='en-US';recognition.continuous=false;recognition.interimResults=false;recognition.maxAlternatives=3;recognition.onresult=event=>finish({text:event.results?.[0]?.[0]?.transcript||'',mode:'browser'});recognition.onerror=event=>{const error=event?.error||'speech-error';if(error==='no-speech'||error==='aborted')finish({text:'',mode:'browser',error});else failVoice(new Error(error))};recognition.onend=()=>finish({text:'',mode:'browser',error:'ended'});if(token!==voiceRun)return finish({text:'',mode:'browser',error:'cancelled'});try{recognition.start()}catch(error){failVoice(error)}})}
  async function listenOnce(token){if(window.IronSixNative?.listenVoice){voiceMode='native';const result=await window.IronSixNative.listenVoice({language:'en-US'});return {text:String(result?.text||''),mode:result?.onDevice?'on-device Android':'Android speech service',error:result?.error||null}}voiceMode='browser';return listenWebOnce(token)}
  async function voiceLoop(token){while(voiceEnabled&&token===voiceRun&&sheet?.classList.contains('show')){setVoiceUi('Listening…','Say a load, reps/RIR, “set done”, “move on”, or “re-lock”.');try{const result=await listenOnce(token);if(!voiceEnabled||token!==voiceRun)break;if(result.mode)voiceMode=result.mode;if(result.text){lastTranscript=result.text;handleVoice(result.text)}else if(result.error!=='aborted'&&result.error!=='cancelled')setVoiceUi('Listening…','No speech heard. Still listening for your next command.')}catch(error){if(!voiceEnabled||token!==voiceRun)break;const message=String(error?.message||error||'').toLowerCase();if(/permission|not-allowed|denied|insufficient/.test(message)){stopVoice();setVoiceUi('Microphone permission is needed','Voice stayed off; camera tracking continues normally.');break}setVoiceUi('Voice had trouble',`Still retrying. ${String(error?.message||'Speech recognition error').slice(0,90)}`)}await sleep(450)}}
  function startVoice(){if(voiceEnabled)return;if(!voiceSupported()){setVoiceUi('Voice is unavailable','This device/browser has no supported speech-recognition interface. Camera and form watch still work.');return}voiceEnabled=true;const token=++voiceRun;setVoiceUi('Starting voice…');void voiceLoop(token)}
  function stopVoice(){voiceEnabled=false;voiceRun++;try{voiceRecognizer?.abort?.()}catch(_){}voiceRecognizer=null;try{window.IronSixNative?.stopVoice?.()}catch(_){}setVoiceUi('Voice is off','Try “185 pounds”, “8 reps”, “RIR 2”, or “set done”.')}
  function toggleVoice(){voiceEnabled?stopVoice():startVoice()}
  function activeSet(card=target){if(!card)return null;const rows=[...card.querySelectorAll('.set-row')],row=rows.find(r=>!r.querySelector('.done')?.classList.contains('active'))||null;if(!row)return null;return {rows,row,index:rows.indexOf(row),weight:row.querySelector('.weight'),reps:row.querySelector('.reps'),rir:row.querySelector('.rir'),done:row.querySelector('.done')}}
  function writeField(input,value,event='input'){if(!input)return false;input.value=String(value);input.dispatchEvent(new Event(event,{bubbles:true}));return true}
  function applyCount(card,reps){const current=activeSet(card);if(!current)return null;writeField(current.reps,reps);return current.reps}
  function completeCurrentSet(command){const current=activeSet();if(!current){setVoiceUi('Exercise already complete','Say “move on” or close the camera assistant.');return false}if(command.bodyweight)writeField(current.weight,'');else if(command.weight!==null)writeField(current.weight,command.weight);if(command.reps!==null)writeField(current.reps,command.reps);if(command.rir!==null)writeField(current.rir,command.rir,'change');const exerciseIndex=Number(target?.dataset.exerciseIndex),key=Number.isFinite(exerciseIndex)?`${exerciseIndex}-${current.index}`:null,saved=key&&typeof activeUser==='function'?activeUser().today?.[key]:null,cameraReps=counter?.state().reps||0;if(command.reps===null&&!String(saved?.reps||'').trim()&&cameraReps)writeField(current.reps,cameraReps);const confirmedReps=command.reps!==null||cameraReps>0||String(saved?.reps||'').trim();if(!confirmedReps){setVoiceUi('I need the actual rep count first','Say “8 reps”, type the reps, or let the camera count at least one rep before “set done”.');return false}if(!current.done.classList.contains('active'))current.done.click();window.IronSixSessionCards?.apply?.();const next=activeSet();if(next){counter?.reset();formEvaluator=formApi?.createEvaluator?.(rule)||null;formState=formEvaluator?.state?.()||null;paintForm(formState);setText('poseReps','0');setVoiceUi(`Set ${current.index+1} saved · set ${next.index+1} ready`,'Stay at the top position and begin when ready. Voice remains on.');return true}const summary=formEvaluator?.summary?.(),index=Number(target?.dataset.exerciseIndex),workout=typeof finalWorkout==='function'&&typeof activeUser==='function'?finalWorkout(activeUser()):[];close();if(Number.isFinite(index)&&window.IronSixSessionCards?.goTo)window.IronSixSessionCards.goTo(Math.min(workout.length,index+1),workout);const note=summary?.primary&&summary.primary.count>=2?' Form watch: '+summary.primary.text:'';if(typeof toast==='function')toast('Exercise complete. Next exercise ready.'+note);return true}
  function handleVoice(transcript){if(!voiceApi?.parseCommand){setVoiceUi('Voice parser did not load','Camera tracking is unchanged.');return}const command=voiceApi.parseCommand(transcript),summary=voiceApi.summary(command);if(command.stopVoice){stopVoice();return}if(command.relock)relock();if(command.complete){completeCurrentSet(command);return}const current=activeSet();if(current){if(command.bodyweight)writeField(current.weight,'');else if(command.weight!==null)writeField(current.weight,command.weight);if(command.reps!==null)writeField(current.reps,command.reps);if(command.rir!==null)writeField(current.rir,command.rir,'change')}if(command.next||command.previous){const workout=typeof finalWorkout==='function'&&typeof activeUser==='function'?finalWorkout(activeUser()):[],index=Number(target?.dataset.exerciseIndex)||0,dest=command.previous?Math.max(0,index-1):Math.min(workout.length,index+1);close();window.IronSixSessionCards?.goTo?.(dest,workout);return}if(summary)setVoiceUi('Heard: '+summary,`Transcript: “${String(transcript).slice(0,80)}”`);else setVoiceUi('I heard you, but did not change the workout','Use a field word or unit: “185 pounds”, “8 reps”, “RIR 2”, or “set done”.')}

  async function open(card,item){if(loading)return;rule=counterApi.ruleFor(item);if(!rule)return;stop();build();target=card;exercise=item;counter=counterApi.createCounter(rule);tracker=counterApi.createTracker(rule);personTracker=isolationApi?.createPersonTracker?.()||null;tracking=null;personState=null;formEvaluator=formApi?.createEvaluator?.(rule)||null;formState=formEvaluator?.state?.()||null;const id=++sessionId;framesSeen=0;framesTracked=0;detectorFrames=0;roiFrames=0;lastPersonDetectAt=-Infinity;fps=0;lastFrameAt=0;lastVideoTime=-1;startedAt=Date.now();lastTranscript='';sheet.classList.add('show');setText('poseTitle',rule.label+' · '+String(item.name||'').slice(0,40));setText('poseSetup',rule.setup);const caution=counterApi.cautionFor(item),cautionNode=el('poseCaution');if(cautionNode){cautionNode.textContent=caution||'';cautionNode.hidden=!caution}setText('poseReps','0');setText('poseReadout','');setText('poseStatus','Starting the camera…');setText('poseLock','Centre yourself and hold still to lock.');paintForm(formState);setVoiceUi('Voice is off','Enable it for hands-free load/reps/RIR and “set done” commands.');const use=el('poseUse');if(use){use.disabled=true;use.textContent='Use count only'}loading=true;try{await startCamera(id);if(id!==sessionId)return;setText('poseStatus','Loading pose + person isolation…');await loadModel();if(id!==sessionId)return;if(!personTracker&&isolationApi)personTracker=isolationApi.createPersonTracker();await keepAwake(id);if(id!==sessionId)return;setText('poseStatus','Centre yourself and hold still while Iron Six isolates you.');cancelAnimationFrame(raf);raf=requestAnimationFrame(tick)}catch(error){if(id!==sessionId)return;const message=error&&error.name==='NotAllowedError'?'Camera permission was declined. Nothing else changed.':(error&&error.message)||'Could not start the camera.';fail(message);stop()}finally{loading=false}}
  function stop(){sessionId++;cancelAnimationFrame(raf);raf=0;stopVoice();personTracker?.reset?.();personTracker=null;personState=null;if(stream){for(const track of stream.getTracks())track.stop();stream=null}if(video)video.srcObject=null;release()}
  function close(){stop();if(sheet)sheet.classList.remove('show')}
  function diagnostics(){const state=counter?counter.state():null;return {version:2,assistantVersion:3,trackingVersion:5,tracking:tracker?tracker.diagnostics():null,isolation:personTracker?personTracker.diagnostics():null,personDetector:!!personDetector,detectorFrames,roiFrames,rule:rule&&rule.id,reps:state?state.reps:0,rejected:state?state.rejected:0,framesSeen,framesTracked,trackedPercent:framesSeen?Math.round(framesTracked/framesSeen*100):0,fps:Math.round(fps),seconds:startedAt?Math.round((Date.now()-startedAt)/1000):0,resolution:video&&video.videoWidth?`${video.videoWidth}x${video.videoHeight}`:null,form:formEvaluator?.summary?.()||null,voice:{enabled:voiceEnabled,mode:voiceMode,lastTranscript:lastTranscript||null},userAgent:navigator.userAgent,log:state?state.log:[]}}
  function copyDiagnostics(){const text=JSON.stringify(diagnostics(),null,2),done=()=>{if(typeof toast==='function')toast('Diagnostics copied')};if(navigator.clipboard&&navigator.clipboard.writeText)navigator.clipboard.writeText(text).then(done).catch(()=>console.log(text));else console.log(text)}
  function useCount(){const state=counter&&counter.state();if(!state||!state.reps||!target)return close();const input=applyCount(target,state.reps);close();if(!input)return;if(typeof toast==='function')toast('Logged '+state.reps+' reps. Check it before you finish the set.');input.focus()}
  function decorate(){const workout=typeof finalWorkout==='function'&&typeof activeUser==='function'?finalWorkout(activeUser()):[];for(const card of document.querySelectorAll('#exerciseList [data-exercise-index]')){if(card.querySelector('.pose-bar'))continue;const item=workout[Number(card.dataset.exerciseIndex)];if(!item||!counterApi.ruleFor(item))continue;const sets=card.querySelector('.sets');if(!sets)continue;const bar=document.createElement('div');bar.className='pose-bar';bar.innerHTML='<button type="button" class="pose-open">Camera + form + voice</button><span>Tracking v5 · opt-in · person-isolated lock</span>';bar.querySelector('.pose-open').addEventListener('click',()=>open(card,item));sets.appendChild(bar)}}
  const original=window.renderExercises;if(typeof original==='function')window.renderExercises=function(){const result=original.apply(this,arguments);try{decorate()}catch(_){}return result};window.addEventListener('pagehide',close);document.addEventListener('visibilitychange',()=>{if(document.hidden)close()});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{try{decorate()}catch(_){}});else try{decorate()}catch(_){}
  window.IronSixPoseSpike={open,close,decorate,diagnostics,applyCount,relock,handleVoice,startVoice,stopVoice,activeSet};
})();
