/* Iron Six camera assistant recovery runtime.
   Pose-only mobile-safe path; person isolation stays disabled until real-phone stability is proven. */
(() => {
  const FLAG='ironSixPoseSpike';
  const VISION='https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@1.0.1/vision_bundle.mjs';
  const WASM='https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@1.0.1/wasm';
  const MODEL='https://storage.googleapis.com/mediapipe-models/pose_landmarker/pose_landmarker_lite/float16/1/pose_landmarker_lite.task';
  function readFlag(){let stored=null;try{stored=localStorage.getItem(FLAG)}catch(_){}const q=new URLSearchParams(location.search||'').get('pose');if(q==='1'||q==='0'){stored=q;try{localStorage.setItem(FLAG,q)}catch(_){}}return stored==='1'}
  if(!readFlag())return;

  const counterApi=window.IronSixRepCounter;
  let formApi=window.IronSixFormCoach,voiceApi=window.IronSixWorkoutVoice;
  if(!counterApi)return;
  const el=id=>document.getElementById(id),setText=(id,v)=>{const n=el(id);if(n)n.textContent=v},sleep=ms=>new Promise(r=>setTimeout(r,ms));
  function helperUrl(src){const u=new URL(src,location.href),share=new URLSearchParams(location.search||'').get('_vercel_share');if(share)u.searchParams.set('_vercel_share',share);return u.href}
  function loadHelper(src,name,ready){if(window[name])return queueMicrotask(()=>ready(window[name]));const s=document.createElement('script');s.src=helperUrl(src);s.async=true;s.onload=()=>window[name]&&ready(window[name]);s.onerror=()=>console.error('[Iron Six] helper load failed',src);document.head.appendChild(s)}
  loadHelper('pose-form-coach.js?v=6','IronSixFormCoach',api=>{formApi=api;if(rule&&!rule.degraded&&!formEvaluator){formEvaluator=api.createEvaluator?.(rule)||null;paintForm(formEvaluator?.state?.()||null)}});
  loadHelper('workout-voice.js?v=1','IronSixWorkoutVoice',api=>{voiceApi=api});

  let sheet=null,video=null,canvas=null,stream=null,landmarker=null,counter=null,tracker=null,rule=null,target=null,formEvaluator=null,formState=null;
  let sessionId=0,loading=false,processing=false,frameHandle=0,timerHandle=0,wake=null,poseDelegate=null,requestedPortrait=true;
  let framesSeen=0,framesTracked=0,rawPoseFrames=0,fps=0,lastFrameAt=0,inferenceErrors=0,lastInferenceError=null;
  let voiceEnabled=false,voiceRun=0,voiceRecognizer=null,voiceMode=null,lastTranscript='',voiceFailures=0;
  const repsConfirmed=new Set();

  function injectStyles(){if(el('poseAssistStyles'))return;const s=document.createElement('style');s.id='poseAssistStyles';s.textContent=`
  .pose-modal{max-width:720px}.pose-head{display:flex;justify-content:space-between;gap:14px;align-items:flex-start}.pose-head h3{margin:0 0 5px}.pose-head p{margin:0 0 6px}.pose-count{text-align:center;min-width:72px;background:var(--surface2);border:1px solid var(--line);border-radius:15px;padding:9px}.pose-count strong{display:block;font-size:28px;line-height:1}.pose-count span{display:block;color:var(--muted);font-size:11px;margin-top:4px}.pose-stage{position:relative;overflow:hidden;border-radius:16px;background:#050607;aspect-ratio:var(--pose-stage-ratio,3/4);margin:12px auto;width:100%}.pose-stage video,.pose-stage canvas{position:absolute;inset:0;width:100%;height:100%;object-fit:contain;transform:scaleX(-1)}.pose-stage canvas{pointer-events:none}.pose-status{position:absolute;left:10px;right:10px;bottom:10px;background:rgba(5,6,7,.78);border:1px solid rgba(255,255,255,.13);border-radius:11px;padding:8px 10px;font-size:12px;font-weight:750}.pose-readout-row{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-top:9px}.pose-readout{font-size:11px;color:var(--muted);line-height:1.45}.pose-copy{border:1px solid var(--line);background:var(--surface2);color:var(--text);border-radius:10px;padding:8px 10px;font-size:11px;font-weight:800}.pose-form,.pose-voice{margin-top:10px;border:1px solid var(--line);background:var(--surface2);border-radius:14px;padding:11px 12px}.pose-form strong,.pose-voice strong{display:block;font-size:12px}.pose-form span,.pose-voice span{display:block;font-size:11px;line-height:1.45;color:var(--muted);margin-top:3px}.pose-voice{display:grid;grid-template-columns:auto 1fr;gap:10px;align-items:center}.pose-voice.on{border-color:rgba(46,229,128,.5)}.pose-bar{display:flex;align-items:center;gap:9px;flex-wrap:wrap;margin-top:11px;padding-top:11px;border-top:1px solid var(--line)}.pose-bar button{border:1px solid rgba(46,229,128,.35);background:rgba(46,229,128,.08);color:var(--accent);border-radius:11px;padding:9px 11px;font-weight:800}.pose-bar span{font-size:11px;color:var(--muted)}@media(min-width:700px){.pose-stage{max-width:520px}}@media(max-width:520px){.pose-modal{padding:14px}.pose-voice{grid-template-columns:1fr}.pose-voice button{width:100%}}`;document.head.appendChild(s)}
  function build(){if(sheet)return sheet;injectStyles();sheet=document.createElement('div');sheet.className='modal-backdrop pose-sheet';sheet.id='poseSheet';sheet.innerHTML=`<div class="modal pose-modal"><div class="pose-head"><div><h3 id="poseTitle">Camera workout assistant</h3><p id="poseSetup">Setting up the camera…</p></div><div class="pose-count"><strong id="poseReps">0</strong><span>reps</span></div></div><div class="pose-stage" id="poseStage"><video id="poseVideo" playsinline muted autoplay></video><canvas id="poseCanvas"></canvas><div class="pose-status" id="poseStatus">Starting…</div></div><div class="pose-readout-row"><span class="pose-readout" id="poseReadout"></span><button type="button" class="pose-copy" id="poseCopy">Copy diagnostics</button></div><div class="pose-readout-row"><span class="helper" id="poseLock" role="status">Stand in view and hold still briefly.</span><button type="button" class="pose-copy" id="poseRelock">Re-lock user</button></div><div class="pose-form"><strong>Form watch</strong><span id="poseFormCue">Waiting for a completed rep.</span></div><div class="pose-voice" id="poseVoice"><button type="button" class="btn secondary" id="poseVoiceToggle">Enable voice</button><div><strong id="poseVoiceState">Voice is off</strong><span id="poseVoiceHint">Try “185 pounds”, “8 reps”, “RIR 2”, or “set done”.</span></div></div><div class="helper">Recovery build: tolerant pose-only tracking. Person detector remains disabled during mobile stability work.</div><div class="cta"><button type="button" class="btn secondary" id="poseClose">Close</button><button type="button" class="btn primary" id="poseUse" disabled>Use count only</button></div></div>`;document.body.appendChild(sheet);video=el('poseVideo');canvas=el('poseCanvas');el('poseClose').onclick=close;el('poseUse').onclick=useCount;el('poseCopy').onclick=copyDiagnostics;el('poseRelock').onclick=relock;el('poseVoiceToggle').onclick=toggleVoice;sheet.addEventListener('click',e=>{if(e.target===sheet)close()});return sheet}

  async function loadModel(){if(landmarker)return landmarker;const vision=await import(VISION),files=await vision.FilesetResolver.forVisionTasks(WASM);const base={modelAssetPath:MODEL,delegate:'GPU'},opts={baseOptions:base,runningMode:'VIDEO',numPoses:1,minPoseDetectionConfidence:.32,minPosePresenceConfidence:.32,minTrackingConfidence:.38};try{landmarker=await vision.PoseLandmarker.createFromOptions(files,opts);poseDelegate='GPU'}catch(gpuError){console.warn('[Iron Six] GPU pose failed; trying CPU',gpuError);landmarker=await vision.PoseLandmarker.createFromOptions(files,{...opts,baseOptions:{...base,delegate:'CPU'}});poseDelegate='CPU'}return landmarker}
  function syncStageAspect(){const stage=el('poseStage');if(stage&&video?.videoWidth&&video?.videoHeight)stage.style.setProperty('--pose-stage-ratio',`${video.videoWidth}/${video.videoHeight}`)}
  async function startCamera(id){if(!navigator.mediaDevices?.getUserMedia)throw new Error('This browser cannot open the camera.');requestedPortrait=window.matchMedia?.('(orientation: portrait)')?.matches ?? ((innerHeight||0)>=(innerWidth||0));const acquired=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'user'},width:{ideal:requestedPortrait?720:1280},height:{ideal:requestedPortrait?1280:720},aspectRatio:{ideal:requestedPortrait?9/16:16/9},frameRate:{ideal:24,max:30}},audio:false});if(id!==sessionId){acquired.getTracks().forEach(t=>t.stop());return}stream=acquired;video.srcObject=stream;await video.play();if(!video.videoWidth)await new Promise(r=>{video.addEventListener('loadedmetadata',r,{once:true});setTimeout(r,2500)});syncStageAspect()}
  async function keepAwake(id){try{if(navigator.wakeLock){const w=await navigator.wakeLock.request('screen');if(id===sessionId)wake=w;else await w.release()}}catch(_){}}
  function releaseWake(){try{wake?.release?.()}catch(_){}wake=null}

  function createRecoveryTracker(){
    const options={lowConfidence:.12,highConfidence:.34,acquireQuality:.20,acquireMs:180,acquireMargin:.06,maxCoastMs:1500,maxPresenceCoastMs:3000,maxEmptyCoastMs:2600,maxCenterCost:1.25,ambiguityMargin:.10,highCost:2.0,lowCost:1.55};
    if(formApi?.createSubjectTracker)return formApi.createSubjectTracker(rule,options);
    return counterApi.createTracker(rule,{confidence:.38,acquireMs:250,lossMs:1200});
  }

  function schedule(){if(!sheet?.classList.contains('show')||!video)return;if(video.requestVideoFrameCallback){frameHandle=video.requestVideoFrameCallback((_now,meta)=>{frameHandle=0;processFrame(meta?.mediaTime!=null?meta.mediaTime*1000:performance.now())})}else{timerHandle=setTimeout(()=>{timerHandle=0;processFrame(performance.now())},80)}}
  function processFrame(frameTs){if(!sheet?.classList.contains('show')||!landmarker||!video)return;if(processing){schedule();return}if(video.readyState<2||!video.videoWidth){schedule();return}processing=true;const now=performance.now();try{let poses=[];try{poses=landmarker.detectForVideo(video,Math.max(frameTs,now))?.landmarks||[];if(poses.length)rawPoseFrames++;lastInferenceError=null}catch(error){inferenceErrors++;lastInferenceError=String(error?.message||error).slice(0,160)}if(lastFrameAt)fps=fps?fps*.85+(1000/Math.max(1,now-lastFrameAt))*.15:1000/Math.max(1,now-lastFrameAt);lastFrameAt=now;framesSeen++;const aspect=video.videoWidth/video.videoHeight,tracking=tracker.push(poses,now,aspect),landmarks=tracking?.landmarks||null;if(landmarks)framesTracked++;if(tracking?.sideChanged){counter.interrupt();formEvaluator?.reset?.();formEvaluator?.interrupt(counter.state().log.length,true)}const side=tracking?.side??0,framed=landmarks?counterApi.framing(rule,landmarks,side,.32):{ok:false,message:tracking?.message||'No pose detected yet.'};const state=counter.push({landmarks,t:now,aspect,side,subjectPresent:!!landmarks,minVisibility:.32,framed:framed.ok});if(formEvaluator)formState=formEvaluator.push({landmarks,side,t:now,aspect,framed:framed.ok,counterState:state});draw(landmarks,state,side);paint(state,{ok:!!landmarks&&framed.ok&&state.measurementValid,message:!framed.ok?framed.message:(tracking?.message||state.message)});paintForm(formState);setText('poseLock',tracking?.message||(landmarks?'Pose locked · keep your working side visible.':'Searching for your pose…'))}catch(error){lastInferenceError=String(error?.message||error).slice(0,160);setText('poseStatus','Analyzer recovered from an error; continuing.')}finally{processing=false;schedule()}}

  function paint(state,frame){setText('poseReps',String(state.reps||0));const use=el('poseUse');if(use){use.disabled=!(state.reps>0);use.textContent=state.reps?`Use ${state.reps} reps only`:'Use count only'}const tracked=framesSeen?Math.round(framesTracked/framesSeen*100):0,raw=framesSeen?Math.round(rawPoseFrames/framesSeen*100):0;setText('poseReadout',[poseDelegate==='CPU'?'CPU mode':poseDelegate||'loading',video?.videoWidth?`${video.videoWidth}×${video.videoHeight}`:'no video',`${Math.round(fps)} fps`,`${raw}% raw pose`,`${tracked}% locked`,state.angle==null?'no angle':`${state.angle}°`,`${state.rejected||0} rejected`].join(' · '));setText('poseStatus',frame.ok?(state.message||'Tracking.'):(frame.message||'Searching…'))}
  function paintForm(state){let text=formEvaluator?(rule?.id==='squat'?'Form watch active — complete a rep with your side visible.':'Rep timing only for this exercise.'):'Form watch loading…';if(state?.paused)text=state.reason||'Form analysis paused.';else if(state?.repeatedCue)text='Coach cue: '+state.repeatedCue.text;else if(state?.latest?.cues?.length)text='Rep '+state.latest.index+' suggestion: '+state.latest.cues[0].text;else if(state?.latest)text='Rep '+state.latest.index+' analyzed.';setText('poseFormCue',text)}
  function draw(landmarks,state,side){if(!canvas||!video?.videoWidth)return;if(canvas.width!==video.videoWidth||canvas.height!==video.videoHeight){canvas.width=video.videoWidth;canvas.height=video.videoHeight}const c=canvas.getContext('2d');c.clearRect(0,0,canvas.width,canvas.height);if(!landmarks)return;const chain=rule.joint[side]||rule.joint[0],chains=rule.id==='squat'?[[side?12:11,side?24:23],chain]:[chain];c.strokeStyle=state.phase==='waiting'||state.phase==='lost'?'#ff8b8b':'#2ee580';c.fillStyle=c.strokeStyle;c.lineWidth=Math.max(3,canvas.width/220);for(const ids of chains){const pts=ids.map(i=>landmarks[i]);if(pts.some(p=>!p||(p.visibility!=null&&p.visibility<.32)))continue;c.beginPath();pts.forEach((p,i)=>{const x=p.x*canvas.width,y=p.y*canvas.height;i?c.lineTo(x,y):c.moveTo(x,y)});c.stroke();for(const p of pts){c.beginPath();c.arc(p.x*canvas.width,p.y*canvas.height,c.lineWidth*1.5,0,Math.PI*2);c.fill()}}}

  function relock(){if(!tracker||!counter)return;tracker.reset();counter.interrupt();formEvaluator?.reset?.();formEvaluator?.interrupt(counter.state().log.length,true);setText('poseLock','Re-lock requested · stand in view and hold still.');setText('poseStatus','Re-locking. Completed reps are kept.');canvas?.getContext('2d')?.clearRect(0,0,canvas.width,canvas.height)}
  function cameraSettings(){try{return stream?.getVideoTracks?.()[0]?.getSettings?.()||null}catch(_){return null}}
  function diagnostics(){const s=counter?.state?.();return {version:5,recoveryRuntime:true,tolerantTracker:true,fullFramePortraitFix:true,requestedPortrait,personDetector:false,poseOnly:true,poseDelegate,framesSeen,rawPoseFrames,rawPosePercent:framesSeen?Math.round(rawPoseFrames/framesSeen*100):0,framesTracked,trackedPercent:framesSeen?Math.round(framesTracked/framesSeen*100):0,fps:Math.round(fps),inferenceErrors,lastInferenceError,tracker:tracker?.diagnostics?.()||null,cameraSettings:cameraSettings(),resolution:video?.videoWidth?`${video.videoWidth}x${video.videoHeight}`:null,reps:s?.reps||0,rejected:s?.rejected||0,voice:{enabled:voiceEnabled,mode:voiceMode,lastTranscript:lastTranscript||null},userAgent:navigator.userAgent}}
  async function copyDiagnostics(){const text=JSON.stringify(diagnostics(),null,2);try{await navigator.clipboard.writeText(text);setText('poseLock','Diagnostics copied.');return}catch(_){}try{const ta=document.createElement('textarea');ta.value=text;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove();setText('poseLock','Diagnostics copied.')}catch(_){window.prompt?.('Copy Iron Six diagnostics',text)}}

  function voiceSupported(){return !!(window.IronSixNative?.listenVoice||(window.SpeechRecognition||window.webkitSpeechRecognition))}
  function setVoiceUi(title,hint){setText('poseVoiceState',title);if(hint!==undefined)setText('poseVoiceHint',hint);el('poseVoice')?.classList.toggle('on',voiceEnabled);const b=el('poseVoiceToggle');if(b)b.textContent=voiceEnabled?'Disable voice':'Enable voice'}
  function stopVoice(){voiceEnabled=false;voiceRun++;try{voiceRecognizer?.abort?.()}catch(_){}voiceRecognizer=null;try{window.IronSixNative?.stopVoice?.()}catch(_){}setVoiceUi('Voice is off','Try “185 pounds”, “8 reps”, “RIR 2”, or “set done”.')}
  async function listenWebOnce(token){const C=window.SpeechRecognition||window.webkitSpeechRecognition;if(!C)throw new Error('Speech recognition unavailable');return new Promise((resolve,reject)=>{const r=new C();voiceRecognizer=r;let done=false;const finish=v=>{if(done)return;done=true;if(voiceRecognizer===r)voiceRecognizer=null;resolve(v)};r.lang='en-US';r.continuous=false;r.interimResults=false;r.onresult=e=>finish({text:e.results?.[0]?.[0]?.transcript||'',mode:'browser'});r.onerror=e=>e.error==='aborted'||e.error==='no-speech'?finish({text:'',mode:'browser',error:e.error}):reject(new Error(e.error||'speech-error'));r.onend=()=>finish({text:'',mode:'browser'});if(token!==voiceRun)return finish({text:'',mode:'browser'});r.start()})}
  async function listenOnce(token){if(window.IronSixNative?.listenVoice){const r=await window.IronSixNative.listenVoice({language:'en-US'});return {text:String(r?.text||''),mode:r?.onDevice?'on-device Android':'Android speech service'}}return listenWebOnce(token)}
  async function voiceLoop(token){while(voiceEnabled&&token===voiceRun&&sheet?.classList.contains('show')){setVoiceUi('Listening…','Say a load, reps/RIR, “set done”, “move on”, or “re-lock”.');try{const r=await listenOnce(token);if(!voiceEnabled||token!==voiceRun)break;voiceMode=r.mode||voiceMode;voiceFailures=0;if(r.text){lastTranscript=r.text;handleVoice(r.text)}}catch(error){if(!voiceEnabled||token!==voiceRun)break;if(++voiceFailures>=3){stopVoice();setVoiceUi('Voice stopped after repeated errors',String(error?.message||error).slice(0,90));break}}await sleep(250)}}
  function startVoice(){if(voiceEnabled)return;if(!voiceSupported()){setVoiceUi('Voice unavailable','Camera tracking still works.');return}voiceEnabled=true;voiceFailures=0;const token=++voiceRun;setVoiceUi('Starting voice…');void voiceLoop(token)}
  function toggleVoice(){voiceEnabled?stopVoice():startVoice()}
  function liveCard(card){if(card?.isConnected)return card;const i=Number((card||target)?.dataset.exerciseIndex);return Number.isFinite(i)?document.querySelector(`#exerciseList [data-exercise-index="${i}"]`)||card:null}
  function activeSet(card=target){card=liveCard(card);if(!card)return null;const rows=[...card.querySelectorAll('.set-row')],row=rows.find(r=>!r.querySelector('.done')?.classList.contains('active'));if(!row)return null;return {rows,row,index:rows.indexOf(row),weight:row.querySelector('.weight'),reps:row.querySelector('.reps'),rir:row.querySelector('.rir'),done:row.querySelector('.done')}}
  function writeField(input,value,event='input'){if(!input)return;input.value=String(value);input.dispatchEvent(new Event(event,{bubbles:true}))}
  function handleVoice(transcript){if(!voiceApi?.parseCommand)return setVoiceUi('Voice parser loading…');const cmd=voiceApi.parseCommand(transcript),summary=voiceApi.summary(cmd);if(cmd.stopVoice)return stopVoice();if(cmd.relock)relock();const current=activeSet();if(current){if(cmd.bodyweight)writeField(current.weight,'');else if(cmd.weight!=null)writeField(current.weight,cmd.weight);if(cmd.reps!=null){writeField(current.reps,cmd.reps);const ei=Number(target?.dataset.exerciseIndex);if(Number.isFinite(ei))repsConfirmed.add(`${ei}-${current.index}`)}if(cmd.rir!=null)writeField(current.rir,cmd.rir,'change');if(cmd.complete){const cameraReps=counter?.state?.().reps||0;if(cmd.reps==null&&cameraReps)writeField(current.reps,cameraReps);if(cmd.reps!=null||cameraReps||repsConfirmed.has(`${target?.dataset.exerciseIndex}-${current.index}`))current.done?.click()}}if(summary)setVoiceUi('Heard: '+summary,`Transcript: “${transcript.slice(0,80)}”`)}

  function applyCount(card,reps){const cur=activeSet(card);if(!cur)return null;writeField(cur.reps,reps);return cur.reps}
  function useCount(){const s=counter?.state?.();if(!s?.reps)return;const input=applyCount(target,s.reps);close();input?.focus?.()}
  async function open(card,item){if(loading)return;rule=counterApi.ruleFor(item);if(!rule)return;stop();build();target=card;counter=counterApi.createCounter(rule);tracker=createRecoveryTracker();formEvaluator=formApi?.createEvaluator?.(rule)||null;formState=formEvaluator?.state?.()||null;framesSeen=framesTracked=rawPoseFrames=inferenceErrors=0;fps=lastFrameAt=0;lastInferenceError=null;const id=++sessionId;sheet.classList.add('show');setText('poseTitle',rule.label+' · '+String(item.name||'').slice(0,40));setText('poseSetup',rule.setup);setText('poseStatus','Starting the camera…');setText('poseReadout','');setText('poseReps','0');setText('poseLock','Stand in view and hold still briefly.');paintForm(formState);setVoiceUi('Voice is off','Enable it for hands-free logging.');loading=true;try{await startCamera(id);if(id!==sessionId)return;setText('poseStatus','Loading pose model…');await loadModel();if(id!==sessionId)return;await keepAwake(id);if(id!==sessionId)return;setText('poseStatus','Pose model ready · finding you…');schedule()}catch(error){setText('poseStatus',error?.message||'Could not start camera analysis.');setText('poseLock','Camera analysis unavailable. Close and reopen to retry.')}finally{loading=false}}
  function stop(){sessionId++;if(frameHandle&&video?.cancelVideoFrameCallback)try{video.cancelVideoFrameCallback(frameHandle)}catch(_){}frameHandle=0;clearTimeout(timerHandle);timerHandle=0;processing=false;stopVoice();if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}if(video)video.srcObject=null;releaseWake()}
  function close(){stop();sheet?.classList.remove('show')}
  function decorate(){const workout=typeof finalWorkout==='function'&&typeof activeUser==='function'?finalWorkout(activeUser()):[];for(const card of document.querySelectorAll('#exerciseList [data-exercise-index]')){if(card.querySelector('.pose-bar'))continue;const item=workout[Number(card.dataset.exerciseIndex)];if(!item||!counterApi.ruleFor(item))continue;const sets=card.querySelector('.sets');if(!sets)continue;const bar=document.createElement('div');bar.className='pose-bar';bar.innerHTML='<button type="button" class="pose-open">Camera + form + voice</button><span>Camera estimates · recovery build</span>';bar.querySelector('.pose-open').onclick=()=>open(card,item);sets.appendChild(bar)}}
  const original=window.renderExercises;if(typeof original==='function')window.renderExercises=function(){const r=original.apply(this,arguments);try{decorate()}catch(_){}return r};window.addEventListener('pagehide',close);document.addEventListener('visibilitychange',()=>{if(document.hidden)close()});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',decorate);else decorate();
  window.IronSixPoseSpike={open,close,decorate,diagnostics,applyCount,relock,handleVoice,startVoice,stopVoice,activeSet};
})();