function renderUserSelect(){const sel=document.getElementById('userSelect');sel.innerHTML=data.users.map(u=>`<option value="${u.id}" ${u.id===data.activeUserId?'selected':''}>${escapeHtml(u.name)}</option>`).join('')}
function renderTodayHeader(){const u=activeUser(),key=u.program.currentWorkoutKey||'lower_strength',variant=currentVariant(u,key),meta=WORKOUT_META[key];document.getElementById('metricWeight').textContent=`${u.weight} lb`;document.getElementById('metricDuration').textContent=`${u.workoutMinutes||60}m`;document.getElementById('todayEyebrow').textContent=`Today · ${variantName(variant)}`;document.getElementById('todayTitle').textContent=meta?.name||'Today’s session';document.getElementById('todayDesc').textContent=`Your sessions complement each other. Benchmark lifts track progress; accessories vary with your completed training.`;const badges=document.getElementById('equipmentBadges');const active=[...EQUIPMENT.filter(([k])=>has(u,k)).map(([,label])=>label),...(u.customEquipment||[])];const shown=(active.length?active:['Bodyweight only']),extra=shown.length-5;badges.innerHTML=shown.slice(0,5).map(x=>`<span class="badge">${escapeHtml(x)}</span>`).join('')+(extra>0?`<span class="badge">+${extra} more</span>`:'')}
function renderDurationPicker(){const u=activeUser(),m=Number(u.workoutMinutes)||60,presets=[15,20,30,45,60],isPreset=presets.includes(m);document.querySelectorAll('.duration-btn').forEach(b=>{const v=b.dataset.minutes;b.classList.toggle('active',v==='custom'?!isPreset:Number(v)===m)});const custom=document.getElementById('customTime');custom.classList.toggle('show',!isPreset);document.getElementById('customMinutes').value=isPreset?'':m;document.getElementById('timeSummary').innerHTML=`<strong>${m}-minute workout:</strong> ${escapeHtml(durationSummary(m))}`}
function setWorkoutMinutes(minutes){const u=activeUser(),value=Number(minutes);if(!Number.isFinite(value)||value<10||value>120){toast('Enter a workout length from 10 to 120 minutes');return}const m=Math.round(value);if(m===u.workoutMinutes){renderDurationPicker();return}const hasLogged=Object.keys(u.today||{}).length>0;if(hasLogged&&!confirm('Changing workout length will archive the current log and build a new session. Saved entries remain recoverable. Continue?')){renderDurationPicker();return}if(window.IronSixJournal&&!window.IronSixJournal.archive(u,'Change duration'))return;u.workoutMinutes=m;u.today={};clearSessionRecommendations(u);saveData();renderAll();toast(`Workout rebuilt for ${m} minutes`)}
function renderEquipmentEditor(){const u=activeUser(),el=document.getElementById('equipmentEditor');el.innerHTML=EQUIPMENT.map(([k,label])=>`<label class="equip"><input type="checkbox" data-equip="${k}" ${has(u,k)?'checked':''}><span>${label}</span></label>`).join('');if(typeof renderCustomEquipmentEditor==='function')renderCustomEquipmentEditor()}
function renderProfileEditor(){const u=activeUser();document.getElementById('editProfileHeading').textContent=`Edit ${u.name}`;document.getElementById('profileName').value=u.name;document.getElementById('bodyWeight').value=u.weight;document.getElementById('age').value=u.age||'';document.getElementById('heightIn').value=u.heightIn||'';document.getElementById('trainingLevel').value=u.trainingLevel||'unknown';document.getElementById('benchBest').value=u.benchBest||'';if(document.getElementById('dumbbellMax'))document.getElementById('dumbbellMax').value=u.capacities?.dumbbellMax||30;if(document.getElementById('barbellMax'))document.getElementById('barbellMax').value=u.capacities?.barbellMax||300;renderEquipmentEditor()}
function renderProfileList(){const el=document.getElementById('profileList');el.innerHTML=data.users.map(u=>`<div class="profile-card ${u.id===data.activeUserId?'active':''}"><div><strong>${escapeHtml(u.name)}</strong><span>${u.weight} lb${u.trainingLevel&&u.trainingLevel!=='unknown'?` • ${u.trainingLevel}`:''} • ${equipmentLabel(u)}</span></div><div class="profile-actions"><button class="iconbtn switch-profile" data-id="${u.id}" aria-label="Switch to ${escapeHtml(u.name)}">✓</button>${data.users.length>1?`<button class="iconbtn delete-profile" data-id="${u.id}" aria-label="Delete ${escapeHtml(u.name)}">×</button>`:''}</div></div>`).join('');el.querySelectorAll('.switch-profile').forEach(b=>b.addEventListener('click',()=>switchUser(b.dataset.id)));el.querySelectorAll('.delete-profile').forEach(b=>b.addEventListener('click',()=>deleteUser(b.dataset.id)))}
function renderPlan(){
  const u=activeUser(),key=u.program.currentWorkoutKey||'lower_strength',variant=currentVariant(u,key),meta=WORKOUT_META[key],nextKey=nextWorkoutKey(u),next=WORKOUT_META[nextKey],memory=u.trainerMemory||{},recommendations=(memory.recommendations||[]).slice(0,3);
  const status=document.getElementById('adaptiveCoachStatus');
  if(!status)return;
  status.classList.add('pr-plan-dashboard');
  status.innerHTML=`<div class="pr-schedule-grid"><article class="pr-schedule-card pr-schedule-current"><span class="pr-kicker">Current session</span><h3>${escapeHtml(meta.name)}</h3><p>${escapeHtml(variantName(variant))} · ${Number(u.workoutMinutes)||60} minutes available</p></article><article class="pr-schedule-card"><span class="pr-kicker">After you complete it</span><h3>${escapeHtml(next.name)}</h3><p>${escapeHtml(workoutScheduleReason(u,nextKey))}</p></article></div>
    <p class="pr-schedule-rule">Rest days keep your place. Changes you make today inform the sessions that follow.</p>
    <details class="pr-analysis pr-coaching-notes"><summary><span><strong>Personal training notes</strong><small>Coach review, muscle coverage and the next variation</small></span></summary><div class="pr-analysis-body"><h3>Coach review</h3><p><strong>${escapeHtml(memory.status||'Learning from your completed workouts')}</strong></p><p>${escapeHtml(memory.summary||'Complete a workout to build your training review.')}</p>${recommendations.length?`<h3>Focus for your training</h3><ul>${recommendations.map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ul>`:''}<h3>Muscle coverage</h3><p>${escapeHtml(muscleCoverageSummary(u))}</p><h3>Next variation</h3><p>${escapeHtml(adaptationStatus(u,key))}</p><p class="helper">Weights, reps and sets come from the training engine and your logged performance. The AI coach can recommend changes and suggest exercises that fit your equipment.</p></div></details>`;
}
