function switchUser(id){if(!data.users.some(u=>u.id===id))return;data.activeUserId=id;saveData();renderAll();toast(`Switched to ${activeUser().name}`)}
function deleteUser(id){const u=data.users.find(x=>x.id===id);if(!u||data.users.length<=1)return;if(!confirm(`Delete ${u.name} and this profile’s local history?`))return;data.users=data.users.filter(x=>x.id!==id);if(data.activeUserId===id)data.activeUserId=data.users[0].id;saveData();renderAll();toast('Profile deleted')}
function openNewUser(){['newUserName','newUserWeight','newUserAge','newUserHeight'].forEach(id=>document.getElementById(id).value='');document.getElementById('newUserLevel').value='unknown';document.getElementById('newUserModal').classList.add('show');setTimeout(()=>document.getElementById('newUserName').focus(),50)}
function closeNewUser(){document.getElementById('newUserModal').classList.remove('show')}
function createUser(){const name=document.getElementById('newUserName').value.trim(),weight=Number(document.getElementById('newUserWeight').value),age=Number(document.getElementById('newUserAge').value)||null,heightIn=Number(document.getElementById('newUserHeight').value)||null,level=document.getElementById('newUserLevel').value;if(!name){toast('Enter a name');return}if(!weight||weight<50||weight>600){toast('Enter a valid weight');return}const u=makeUser(name,Math.round(weight),{...DEFAULT_EQUIPMENT});u.age=age;u.heightIn=heightIn;u.trainingLevel=level;u.benchBest='';data.users.push(u);data.activeUserId=u.id;saveData();closeNewUser();renderAll();showView('profiles');toast(`${u.name} created`)}
function saveProfile(){const u=activeUser(),name=document.getElementById('profileName').value.trim(),weight=Number(document.getElementById('bodyWeight').value);if(!name){toast('Name is required');return}if(!weight||weight<50||weight>600){toast('Enter a valid weight');return}u.name=name;u.weight=Math.round(weight);u.age=Number(document.getElementById('age').value)||null;u.heightIn=Number(document.getElementById('heightIn').value)||null;u.trainingLevel=document.getElementById('trainingLevel').value||'unknown';u.benchBest=document.getElementById('benchBest').value.trim();if(document.getElementById('dumbbellMax'))u.capacities.dumbbellMax=Math.max(5,Number(document.getElementById('dumbbellMax').value)||30);if(document.getElementById('barbellMax'))u.capacities.barbellMax=Math.max(45,Number(document.getElementById('barbellMax').value)||300);EQUIPMENT.forEach(([k])=>{u.equipment[k]=document.querySelector(`[data-equip="${k}"]`).checked});u.today={};saveData();renderAll();toast('Profile saved • recommendations rebuilt')}
function finishWorkout(){const u=activeUser(),workout=finalWorkout(u),done=Object.values(u.today||{}).filter(x=>x.done).length;if(done<Math.max(3,Math.floor(workout.reduce((a,e)=>a+e.sets,0)*.45))&&!confirm('Only part of the workout is marked complete. Finish anyway?'))return;const key=u.program.currentWorkoutKey||'lower_strength',variant=currentVariant(u,key);const details=workout.map((exercise,ei)=>({name:exercise.name,base:exercise.base,seedKey:exercise.seedKey,sets:Array.from({length:exercise.sets},(_,i)=>{const x=u.today[`${ei}-${i}`]||{};return {weight:x.weight||'',reps:x.reps||'',rir:x.rir||'',done:!!x.done}}).filter(x=>x.done)})).filter(d=>d.sets.length);const planned=workout.reduce((a,e)=>a+e.sets,0);u.history.unshift({ts:Date.now(),date:new Date().toLocaleDateString(),name:WORKOUT_META[key].name,workoutKey:key,variant:variantLabel(variant),sets:done,plannedSets:planned,duration:u.workoutMinutes||60,details});u.history=u.history.slice(0,120);u.program.exposures[key]=(Number(u.program.exposures[key])||0)+1;const before=Number(u.program.unlocked[key])||1;const after=variantUnlocked(u,key);if(after>before)u.program.lastAdaptation=`Unlocked Variant ${variantLabel(after-1)} for ${WORKOUT_META[key].name} after ${exposureStats(u,key).successful} successful exposures.`;u.program.currentWorkoutKey=nextWorkoutKey(u);u.today={};saveData();renderAll();toast(after>before?'Workout saved • new variant unlocked':'Workout saved • next session ready')}
function resetWorkout(){const u=activeUser();if(confirm('Clear this user’s current logged sets?')){u.today={};saveData();renderExercises();toast('Workout reset')}}
function showView(id){document.querySelectorAll('.navbtn').forEach(x=>x.classList.toggle('active',x.dataset.view===id));document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));window.scrollTo({top:0,behavior:'smooth'})}
function escapeHtml(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.__toastTimer);window.__toastTimer=setTimeout(()=>t.classList.remove('show'),1900)}
function renderAll(){renderUserSelect();renderTodayHeader();renderDurationPicker();renderProfileList();renderProfileEditor();renderHistory();renderPlan();const u=activeUser();document.getElementById('energy').value=String(u.readiness?.energy||4);document.getElementById('soreness').value=String(u.readiness?.soreness||1);renderExercises();const n=document.getElementById('readinessNote');if((u.readiness?.soreness||1)>=4)n.innerHTML='<strong>Adjustment:</strong> High soreness detected. Iron Six removes fatigue-sensitive work and trims volume.';else if((u.readiness?.energy||4)<=2)n.innerHTML='<strong>Adjustment:</strong> Low energy detected. Priority work stays; accessory volume is reduced.';else n.innerHTML='<strong>Plan:</strong> Normal session. Compounds target roughly 1–2 RIR; accessories can finish closer to failure with clean form.'}
document.querySelectorAll('.duration-btn').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.minutes==='custom'){document.getElementById('customTime').classList.add('show');document.getElementById('customMinutes').focus();document.querySelectorAll('.duration-btn').forEach(x=>x.classList.toggle('active',x===b));}else setWorkoutMinutes(Number(b.dataset.minutes))}));document.getElementById('applyCustomTime').addEventListener('click',()=>setWorkoutMinutes(document.getElementById('customMinutes').value));document.getElementById('customMinutes').addEventListener('keydown',e=>{if(e.key==='Enter')setWorkoutMinutes(e.target.value)});document.getElementById('userSelect').addEventListener('change',e=>switchUser(e.target.value));document.getElementById('quickAddUser').addEventListener('click',openNewUser);document.getElementById('addUserBtn').addEventListener('click',openNewUser);document.getElementById('cancelNewUser').addEventListener('click',closeNewUser);document.getElementById('createNewUser').addEventListener('click',createUser);document.getElementById('newUserModal').addEventListener('click',e=>{if(e.target.id==='newUserModal')closeNewUser()});document.getElementById('saveProfile').addEventListener('click',saveProfile);document.getElementById('energy').addEventListener('change',readiness);document.getElementById('soreness').addEventListener('change',readiness);document.getElementById('finishBtn').addEventListener('click',finishWorkout);document.getElementById('resetBtn').addEventListener('click',resetWorkout);document.querySelectorAll('.navbtn').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));saveData();renderAll();
function loadIronSixScript(src){return new Promise(resolve=>{const s=document.createElement('script');s.src=src;s.onload=()=>resolve(true);s.onerror=()=>resolve(false);document.body.appendChild(s)})}
(async()=>{await loadIronSixScript('exercise-guide.js');await loadIronSixScript('exercise-visuals.js');await loadIronSixScript('local-ai-fallback.js');await loadIronSixScript('coach.js');if(Number.isInteger(window.__pendingExerciseCoach)&&typeof window.openExerciseCoach==='function'){const i=window.__pendingExerciseCoach;delete window.__pendingExerciseCoach;window.openExerciseCoach(i)}await loadIronSixScript('cloud-sync.js')})();
