function build_back(variant,u){
 const v=variant%3;
 const O={};

  const vertical=v===1?[ex('Chin-Up',['pullup'],'4 × 5–10',4,'Priority','Vertical pull','pullup',1),ex('Band Lat Pulldown',['bands'],'4 × 10–15',4,'Priority','Vertical pull','pullup',1),ex('Prone Lat Pull',[],'4 × 10–15',4,'Priority','Vertical pull','pullup',1)]:[ex('Pull-Up',['pullup'],'4 × 5–10',4,'Priority','Vertical pull','pullup',1),ex('Band Lat Pulldown',['bands'],'4 × 10–15',4,'Priority','Vertical pull','pullup',1),ex('Prone Lat Pull',[],'4 × 10–15',4,'Priority','Vertical pull','pullup',1)];
  const row=v===1?[ex('Meadows Row',['barbell','landmine'],'4 × 6–10 each side',4,'Priority','Horizontal pull','row',1),ex('One-Arm Dumbbell Row',['dumbbells','bench'],'4 × 8–12 each side',4,'Priority','Horizontal pull','row',1),ex('Barbell Row',['barbell'],'4 × 6–10',4,'Priority','Horizontal pull','row',1),ex('Band Row',['bands'],'4 × 12–20',4,'Priority','Horizontal pull','row',1)]:v===2?[ex('Landmine T-Bar Row',['barbell','landmine'],'4 × 6–10',4,'Priority','Horizontal pull','row',1),ex('Chest-Supported Dumbbell Row',['dumbbells','bench'],'4 × 8–12',4,'Priority','Horizontal pull','row',1),ex('Pendlay Row',['barbell'],'4 × 5–8',4,'Priority','Horizontal pull','row',1),ex('Band Row',['bands'],'4 × 12–20',4,'Priority','Horizontal pull','row',1)]:[ex('Barbell Row',['barbell'],'4 × 6–10',4,'Priority','Horizontal pull','row',1),ex('Landmine Row',['barbell','landmine'],'4 × 6–10',4,'Priority','Horizontal pull','row',1),ex('One-Arm Dumbbell Row',['dumbbells','bench'],'4 × 8–12 each side',4,'Priority','Horizontal pull','row',1),ex('Band Row',['bands'],'4 × 12–20',4,'Priority','Horizontal pull','row',1)];
  const rear=[ex('Band Face Pull',['bands'],'3 × 15–25',3,'Rear delts','Scapular pull','rear_delt'),ex('Dumbbell Rear-Delt Row',['dumbbells'],'3 × 12–20',3,'Rear delts','Scapular pull','rear_delt'),ex('Prone Y-T Raise',['bench'],'3 × 10–15',3,'Rear delts','Scapular pull','rear_delt')];
  const straight=[ex('Band Straight-Arm Pulldown',['bands'],'3 × 12–20',3,'Lats','Lat isolation','lat_iso'),ex('Dumbbell Pullover',['dumbbells','bench'],'3 × 10–15',3,'Lats','Lat isolation','lat_iso'),ex('Isometric Lat Press',[],'3 × 20–30 sec',3,'Lats','Lat isolation','lat_iso')];
  const curl=[ex('Barbell Curl',['barbell'],'3 × 6–10',3,'Biceps','Elbow flexion','curl'),ex('Dumbbell Curl',['dumbbells'],'3 × 8–12',3,'Biceps','Elbow flexion','curl'),ex('Band Curl',['bands'],'3 × 12–20',3,'Biceps','Elbow flexion','curl')];
  return [slot(u,vertical),slot(u,row),slot(u,rear),slot(u,straight),slot(u,curl)];
 
}
