function build_lower_strength(variant,u){
 const v=variant%3;
 const O={};

  O.primary=v===1?[
    ex('Paused Barbell Back Squat',['barbell','rack'],'4 × 4–6 • 1 sec pause',4,'Priority','Primary squat','squat',1),ex('Landmine Squat',['barbell','landmine'],'4 × 6–10',4,'Priority','Primary squat','squat',1),ex('Goblet Squat',['dumbbells'],'4 × 8–12',4,'Priority','Primary squat','squat',1),ex('Tempo Bodyweight Squat',[],'4 × 12–20 • 3 sec down',4,'Priority','Primary squat','squat',1)
   ]:v===2?[
    ex('Barbell Box Squat',['barbell','rack','bench'],'4 × 5–7',4,'Priority','Primary squat','squat',1),ex('Landmine Hack Squat',['barbell','landmine'],'4 × 8–12',4,'Priority','Primary squat','squat',1),ex('Dumbbell Front Squat',['dumbbells'],'4 × 8–12',4,'Priority','Primary squat','squat',1),ex('1½-Rep Bodyweight Squat',[],'4 × 10–16',4,'Priority','Primary squat','squat',1)
   ]:[
    ex('Barbell Back Squat',['barbell','rack'],'1 top set × 4–6, then 3 × 6–8',4,'Priority','Primary squat','squat',1),ex('Landmine Squat',['barbell','landmine'],'4 × 8–12',4,'Priority','Primary squat','squat',1),ex('Goblet Squat',['dumbbells'],'4 × 8–15',4,'Priority','Primary squat','squat',1),ex('Tempo Bodyweight Squat',[],'4 × 15–25 • 3 sec down',4,'Priority','Primary squat','squat',1)
   ];
  O.unilateral=v===1?[ex('Dumbbell Bulgarian Split Squat',['dumbbells','bench'],'3 × 8–12 each leg',3,'Hypertrophy','Single-leg work','split_squat'),ex('Landmine Reverse Lunge',['barbell','landmine'],'3 × 8–12 each leg',3,'Landmine','Single-leg work','split_squat'),ex('Bodyweight Split Squat',[],'3 × 15–20 each leg',3,'Hypertrophy','Single-leg work','split_squat')]:[ex('Landmine Reverse Lunge',['barbell','landmine'],'3 × 8–12 each leg',3,'Landmine','Single-leg work','split_squat'),ex('Dumbbell Bulgarian Split Squat',['dumbbells','bench'],'3 × 8–12 each leg',3,'Hypertrophy','Single-leg work','split_squat'),ex('Bodyweight Split Squat',[],'3 × 15–20 each leg',3,'Hypertrophy','Single-leg work','split_squat')];
  O.hinge=v===2?[ex('Barbell Good Morning',['barbell','rack'],'3 × 6–10',3,'Posterior','Hip hinge','hinge',1),ex('Landmine Romanian Deadlift',['barbell','landmine'],'3 × 8–12',3,'Posterior','Hip hinge','hinge',1),ex('Dumbbell Romanian Deadlift',['dumbbells'],'3 × 10–15',3,'Posterior','Hip hinge','hinge',1),ex('Single-Leg Hip Hinge',[],'3 × 12–15 each leg',3,'Posterior','Hip hinge','hinge',1)]:[ex('Barbell Romanian Deadlift',['barbell'],'3 × 6–10',3,'Posterior','Hip hinge','hinge',1),ex('Landmine Romanian Deadlift',['barbell','landmine'],'3 × 8–12',3,'Posterior','Hip hinge','hinge',1),ex('Dumbbell Romanian Deadlift',['dumbbells'],'3 × 10–15',3,'Posterior','Hip hinge','hinge',1),ex('Single-Leg Hip Hinge',[],'3 × 12–15 each leg',3,'Posterior','Hip hinge','hinge',1)];
  O.glute=[ex('Barbell Hip Thrust',['barbell','bench'],'3 × 8–12',3,'Glutes','Hip extension','hip_thrust'),ex('Dumbbell Hip Thrust',['dumbbells','bench'],'3 × 10–15',3,'Glutes','Hip extension','hip_thrust'),ex('Banded Hip Thrust',['bands'],'3 × 15–25',3,'Glutes','Hip extension','hip_thrust'),ex('Single-Leg Glute Bridge',[],'3 × 12–20 each leg',3,'Glutes','Hip extension','hip_thrust')];
  O.ham=[ex('Band Hamstring Curl',['bands'],'3 × 15–25',3,'Accessory','Knee flexion','ham_curl'),ex('Hamstring Walkout',[],'3 × 8–15',3,'Accessory','Knee flexion','ham_curl')];
  O.calf=[ex('Weighted Standing Calf Raise',['dumbbells'],'4 × 10–15',4,'Accessory','Calves','calves'),ex('Barbell Standing Calf Raise',['barbell','rack'],'4 × 10–15',4,'Accessory','Calves','calves'),ex('Single-Leg Calf Raise',[],'4 × 15–25 each side',4,'Accessory','Calves','calves')];
  O.core=v===1?[ex('Landmine Rotation',['barbell','landmine'],'3 × 8–12 each side',3,'Core','Rotational core','core'),ex('Ab Wheel Rollout',['abwheel'],'3 × 6–12',3,'Core','Anterior core','core'),ex('Band Pallof Press',['bands'],'3 × 10–15 each side',3,'Core','Anterior core','core'),ex('Hard-Style Plank',[],'3 × 20–45 sec',3,'Core','Anterior core','core')]:[ex('Ab Wheel Rollout',['abwheel'],'3 × 6–12',3,'Core','Anterior core','core'),ex('Landmine Rotation',['barbell','landmine'],'3 × 8–12 each side',3,'Core','Rotational core','core'),ex('Band Pallof Press',['bands'],'3 × 10–15 each side',3,'Core','Anterior core','core'),ex('Hard-Style Plank',[],'3 × 20–45 sec',3,'Core','Anterior core','core')];
  return [slot(u,O.primary),slot(u,O.unilateral),slot(u,O.hinge),slot(u,O.glute),slot(u,O.ham),slot(u,O.calf),slot(u,O.core)];
 
}
