const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const {JSDOM}=require('jsdom');

test('native API routing and auth callbacks stay on approved endpoints',async()=>{
  const {apiUrl,API_ORIGIN,authCode,bridgeCallback}=await import('../native/runtime.mjs');
  assert.equal(apiUrl('/api/coach','https://localhost'),API_ORIGIN+'/api/coach');
  assert.equal(apiUrl('/api/config?test=1','https://localhost'),API_ORIGIN+'/api/config?test=1');
  assert.equal(apiUrl('/api/auth-status','https://localhost'),API_ORIGIN+'/api/auth-status');
  assert.equal(apiUrl('/assets/exercises/push-ups-1.png','https://localhost'),'/assets/exercises/push-ups-1.png');
  assert.equal(apiUrl('https://other.test/api/coach','https://localhost'),'https://other.test/api/coach');
  assert.equal(authCode('https://evil.test/?code=hello'),null);
  assert.equal(authCode('com.ironsix.training://wrong/callback?code=hello'),null);
  assert.equal(authCode('com.ironsix.training://auth/callback#access_token=secret'),null);
  assert.deepEqual(authCode('com.ironsix.training://auth/callback?code=hello'),{code:'hello',flowId:undefined});
  const token='x'.repeat(120);
  assert.deepEqual(bridgeCallback('com.ironsix.training://auth/callback#nomad_access_token='+token),{token});
  assert.equal(bridgeCallback('com.ironsix.training://wrong/callback#nomad_access_token='+token),null);
});

test('native callbacks handle PKCE, bridged Google, cancellation, safe areas and background saves',async()=>{
  const {installNative,AUTH_REDIRECT}=await import('../native/runtime.mjs');
  const dom=new JSDOM('<div id="today" class="active"></div><div class="modal-backdrop show"><button id="closeExerciseSwap">Cancel</button></div>',{url:'https://localhost'});
  const win=dom.window,events={},calls=[],messages=[],bridges=[];
  win.fetch=async(input,options)=>{calls.push(['fetch',input,options]);return {ok:true}};
  win.IronSixCircuit={pause:()=>calls.push(['pause'])};win.saveData=()=>calls.push(['save']);
  win.IronSixCloud={syncNow:()=>calls.push(['sync'])};
  win.addEventListener('ironsix:google-bridge',event=>bridges.push(event.detail));
  const App={addListener:async(name,fn)=>{events[name]=fn},getLaunchUrl:async()=>({url:AUTH_REDIRECT+'?code=valid-code'}),minimizeApp:async()=>calls.push(['minimize'])};
  const Browser={open:async({url})=>calls.push(['open',url]),close:async()=>calls.push(['close'])};
  const client={auth:{exchangeCodeForSession:async code=>{calls.push(['exchange',code]);return {data:{session:{}}}},stopAutoRefresh:()=>calls.push(['stop']),startAutoRefresh:()=>calls.push(['start'])}};
  const native=installNative({win,App,Browser,createClient:()=>client,WorkoutBackup:{save:async({json})=>{calls.push(['export',json]);return {saved:true}}}});
  assert.equal(native.authOptions.flowType,'pkce');assert.equal(native.authOptions.detectSessionInUrl,false);
  assert(win.document.documentElement.classList.contains('iron-six-native'));
  assert.match(win.document.getElementById('ironSixNativeInsets').textContent,/safe-area-inset-top/);
  await native.connectCloud(client,message=>messages.push(message));
  events.appUrlOpen({url:AUTH_REDIRECT+'?code=valid-code'});
  await new Promise(resolve=>setImmediate(resolve));
  assert.equal(calls.filter(c=>c[0]==='exchange').length,1);
  const bridgeToken='g'.repeat(160);
  events.appUrlOpen({url:AUTH_REDIRECT+'#nomad_access_token='+bridgeToken});
  await new Promise(resolve=>setImmediate(resolve));
  assert.equal(bridges.length,1);assert.equal(bridges[0].token,bridgeToken);
  events.appUrlOpen({url:AUTH_REDIRECT+'?bridge_error=access_denied'});
  await new Promise(resolve=>setImmediate(resolve));
  assert(messages.at(-1).includes('cancelled'));
  events.appUrlOpen({url:AUTH_REDIRECT+'?error=access_denied&error_description=%3Cscript%3E'});
  await new Promise(resolve=>setImmediate(resolve));
  assert(messages.at(-1).includes('cancelled'));assert(!messages.at(-1).includes('script'));
  events.appStateChange({isActive:false});events.appStateChange({isActive:true});
  for(const action of ['pause','save','stop','start','sync'])assert(calls.some(c=>c[0]===action));
  await win.fetch('/api/coach',{method:'POST',body:'test'});assert(calls.at(-1)[1].startsWith('https://iron-six-training-'));assert.equal(calls.at(-1)[2].body,'test');
  const backup=JSON.stringify({exportedAt:new Date().toISOString(),profiles:{users:[]},entries:[]});
  await native.exportBackup(backup);assert.equal(calls.at(-1)[0],'export');assert.equal(calls.at(-1)[1],backup);
  await assert.rejects(native.exportBackup('{}'),/empty or invalid/);
  let closed=false;win.document.getElementById('closeExerciseSwap').onclick=()=>{closed=true};events.backButton();assert(closed);
  win.HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','')};
  win.HTMLDialogElement.prototype.close=function(){this.removeAttribute('open');this.dispatchEvent(new win.Event('close'))};
  const imageLink=win.document.createElement('a');imageLink.href='/assets/exercises/push-ups-1.png';imageLink.innerHTML='<img alt="Push-up position 1">';win.document.body.append(imageLink);imageLink.click();
  assert(win.document.querySelector('dialog[open] img').src.endsWith('/assets/exercises/push-ups-1.png'));
  events.backButton();assert.equal(win.document.querySelector('dialog'),null,'Android Back closes the image instead of leaving the workout');
  await assert.rejects(native.openOAuth('javascript:alert(1)'));
  dom.window.close();
});

test('Android configuration packages direct and dynamic runtime assets with limited permissions',()=>{
  require('node:child_process').execFileSync(process.execPath,['scripts/build-android-web.mjs'],{stdio:'pipe'});
  const config=JSON.parse(fs.readFileSync('capacitor.config.json','utf8'));
  assert.equal(config.appId,'com.ironsix.training');assert.equal(config.webDir,'www');assert(!config.server.url);
  const manifest=fs.readFileSync('android/app/src/main/AndroidManifest.xml','utf8');
  assert(manifest.includes('android:usesCleartextTraffic="false"'));assert(manifest.includes('android:host="auth" android:path="/callback"'));
  assert(!manifest.includes('READ_EXTERNAL_STORAGE'));assert(!manifest.includes('WRITE_EXTERNAL_STORAGE'));
  const source=fs.readFileSync('scripts/build-android-web.mjs','utf8');assert(!source.includes("cp(resolve(root,'api')"));
  const index=fs.readFileSync('www/index.html','utf8');assert(index.indexOf('native.js')<index.indexOf('core.js'));
  assert(fs.statSync('www/native.js').size>1000);
  for(const match of index.matchAll(/<script src="([^"?]+)(?:\?[^" ]*)?"/g))assert(fs.existsSync('www/'+match[1]),match[1]);
  for(const runtime of ['coach-recovery.js','auth-hardening.js','account-polish.js'])assert(fs.existsSync('www/'+runtime),`missing dynamic runtime asset ${runtime}`);
  assert(!fs.existsSync('www/api'));assert(!fs.existsSync('www/.env'));
  const nativeSource=fs.readFileSync('native/runtime.mjs','utf8');assert(nativeSource.includes('safe-area-inset-top'));assert(nativeSource.includes('nomad_access_token'));
  const backupPlugin=fs.readFileSync('android/app/src/main/java/com/ironsix/training/WorkoutBackupPlugin.java','utf8');
  assert(backupPlugin.includes('payload.has("entries")'));assert(!backupPlugin.includes('call.getString("json", "{}")'));
  for(const record of require('../exercise-media-catalog.js').records)for(const path of record.frames)assert(fs.existsSync('www/'+path),path);
});
