const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const context={window:{},document:{addEventListener(){},getElementById(){return null}},Date,Math,Number,Array,Object,String,JSON,setTimeout(){}};
context.window=context;
vm.createContext(context);
vm.runInContext(fs.readFileSync('trainer-intelligence-v2.js','utf8'),context);
const now=Date.now();
const session=(days,sets,energy=4,rir=2)=>({ts:now-days*864e5,readiness:{energy},details:[{sets:Array.from({length:sets},()=>({weight:100,reps:10,rir,done:true}))}]});
const fresh={history:[session(1,8,4,2),session(4,8,4,2),session(8,8,4,2)],trainingFeedback:[{ts:now-864e5,feedback:'right'}]};
const a=context.IronSixTrainerV2.trainingState(fresh,now);
assert(['Build','Learning'].includes(a.phase));
assert(a.fatigue<45);
const fatigued={history:[session(1,18,2,0),session(3,18,2,0),session(6,18,2,0),session(9,12,2,1)],trainingFeedback:Array.from({length:7},(_,i)=>({ts:now-(i+1)*864e5,feedback:i===0?'pain':'hard'}))};
const b=context.IronSixTrainerV2.trainingState(fatigued,now);
assert.equal(b.phase,'Deload suggested');
assert(b.fatigue>=65);
assert.match(b.recommendation,/25–35%/);
const progress={history:[session(1,8,5,3),session(4,8,5,3),session(8,8,5,3)],trainingFeedback:Array.from({length:5},(_,i)=>({ts:now-(i+1)*864e5,feedback:'easy'}))};
const c=context.IronSixTrainerV2.trainingState(progress,now);
assert.equal(c.phase,'Progress');
