const MODEL=process.env.GROQ_MODEL||'openai/gpt-oss-20b';
function clamp(n,min,max){return Math.max(min,Math.min(max,n))}
function cleanJson(value){const raw=String(value||'').trim();try{return JSON.parse(raw)}catch(_){}const a=raw.indexOf('{'),b=raw.lastIndexOf('}');if(a>=0&&b>a){try{return JSON.parse(raw.slice(a,b+1))}catch(_){}}return {}}
function safeText(value,max=180){return String(value||'').replace(/[<>]/g,'').trim().slice(0,max)}
function safePlan(input){return (Array.isArray(input)?input:[]).slice(0,12).map((x,index)=>({index:Number.isInteger(x.index)?x.index:index,name:safeText(x.name,80),base:safeText(x.base,50),load:clamp(Number(x.load)||0,0,1500),reps:clamp(Math.round(Number(x.reps)||8),1,30),repMin:clamp(Math.round(Number(x.repMin)||1),1,30),repMax:clamp(Math.round(Number(x.repMax)||30),1,30),sets:clamp(Math.round(Number(x.sets)||1),1,10)})).filter(x=>x.name&&x.base)}
function fallback(plan,reason='Validated calculations are ready for the next workout.') {return {status:'Trainer review complete',summary:reason,recommendations:['Log weight, reps, and RIR on every working set for sharper future decisions.'],adjustments:[],verifiedPlan:plan.map(x=>({...x,verifiedLoad:x.load,verifiedReps:clamp(x.reps,x.repMin,x.repMax),verifiedSets:x.sets})),model:'validated-calculation'}}

export default async function handler(req,res){
  if(req.method!=='POST')return res.status(405).json({error:'POST required'});
  const plan=safePlan(req.body?.nextWorkout);if(!plan.length)return res.status(400).json({error:'Next workout plan required'});
  if(!process.env.GROQ_API_KEY)return res.status(200).json(fallback(plan,'The next workout passed local consistency checks; cloud review was unavailable.'));
  const completed=req.body?.completedSession||{},history=Array.isArray(req.body?.history)?req.body.history.slice(0,8):[];
  const system=`You are the long-term programming reviewer for a strength and hypertrophy app. Review the completed workout, up to eight recent sessions, readiness, and the complete deterministic next-workout plan. Return only JSON with this exact shape: {"summary":"one short useful assessment","recommendations":["up to three short priorities"],"adjustments":[{"base":"exact supplied movement base","factor":1.00,"reason":"short reason"}],"checks":[{"index":0,"load":100,"reps":8,"sets":3}]}.
Rules: every next-workout exercise must appear once in checks. Copy its deterministic load, reps, and sets unless a recent multi-session trend supports a small change. Adjustment factors must be 0.97 to 1.03 and apply only to exact supplied base values. A single workout is weak evidence. Missing RIR lowers confidence. Do not increase load after missed reps, repeated RIR 0, low energy, high soreness, or declining estimated strength. Do not change reps outside the supplied range, sets by more than one, or load by more than 5 percent. Never optimize through pain or diagnose. Consistency and recovery take priority over novelty.`;
  try{
    const response=await fetch('https://api.groq.com/openai/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${process.env.GROQ_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model:MODEL,messages:[{role:'system',content:system},{role:'user',content:JSON.stringify({profile:req.body?.profile||{},completedSession:completed,recentHistory:history,nextWorkout:plan})}],temperature:.1,max_completion_tokens:900})});
    const body=await response.json();if(!response.ok)return res.status(200).json(fallback(plan,'The next workout passed local consistency checks; Groq review was temporarily unavailable.'));
    const parsed=cleanJson(body?.choices?.[0]?.message?.content),allowedBases=new Set(plan.map(x=>x.base)),byIndex=new Map((Array.isArray(parsed.checks)?parsed.checks:[]).map(x=>[Number(x.index),x]));
    const adjustments=(Array.isArray(parsed.adjustments)?parsed.adjustments:[]).filter(x=>allowedBases.has(String(x.base))).slice(0,12).map(x=>({base:String(x.base),factor:Number(clamp(Number(x.factor)||1,.97,1.03).toFixed(3)),reason:safeText(x.reason||'Groq verified this conservative adjustment.',140),verified:true}));
    const verifiedPlan=plan.map(x=>{const check=byIndex.get(x.index)||{},maxDelta=x.load*.05,rawLoad=Number(check.load),verifiedLoad=x.load?clamp(Number.isFinite(rawLoad)?rawLoad:x.load,x.load-maxDelta,x.load+maxDelta):0;return {...x,verifiedLoad:Math.round(verifiedLoad/5)*5,verifiedReps:clamp(Math.round(Number(check.reps)||x.reps),x.repMin,x.repMax),verifiedSets:clamp(Math.round(Number(check.sets)||x.sets),Math.max(1,x.sets-1),Math.min(10,x.sets+1))}});
    return res.status(200).json({status:'Groq trainer review complete',summary:safeText(parsed.summary||'Groq reviewed the completed session and verified the next workout.',220),recommendations:(Array.isArray(parsed.recommendations)?parsed.recommendations:[]).slice(0,3).map(x=>safeText(x,160)).filter(Boolean),adjustments,verifiedPlan,model:MODEL});
  }catch(err){return res.status(200).json(fallback(plan,'The next workout passed local consistency checks; Groq review will try again after a later session.'))}
}
